### ISSUE TITLE
java.io.FileNotFoundException formatting deleted git file

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalafmt#1000]
This template is a guideline, not a strict requirement.
- **Version**: 1.1.0
- **Integration**: bootstraped
- **Configuration**:
```
project.git = true
```

## Steps

I ran scalafmt like this:

```bash
add file to git
commit
delete file from git
run scalafmt
```

## Problem

```
 bin/scalafmt
Exception in thread "main" java.io.FileNotFoundException: /home/gui/scastie/client/src/test/scala/com.olegych.scastie.client/NameChangerSpec.scala (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.scalafmt.util.FileOps$.readFile(FileOps.scala:63)
        at org.scalafmt.util.FileOps$.readFile(FileOps.scala:51)
        at org.scalafmt.cli.InputMethod$FileContents.readInput(InputMethod.scala:40)
        at org.scalafmt.cli.Cli$.org$scalafmt$cli$Cli$$handleFile(Cli.scala:112)
        at org.scalafmt.cli.Cli$$anonfun$run$1.apply(Cli.scala:173)
        at org.scalafmt.cli.Cli$$anonfun$run$1.apply(Cli.scala:171)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:169)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

## Expectation

it should know from the git status that the file is deleted

## Workaround

commit then format

**Comment by pjrt** [comment]
Reproduced. Yep, there are a couple of issues with git and file lookup (more than likely from my changes on 1.0). 

As a workaround, you can do `scalafmt --diff-branch HEAD`. That uses a different strategy to find files and seems to understand that the file is deleted.

**Comment by MasseGuillaume** [comment]
Awesome, thanks!

**Comment by robbyki** [comment]
this is really plaguing me right now and I can't get scalafmt to stop looking for the deleted file. I've already tried to commit and then scalafmt. How do I get it to stop giving me the file not found exception after removing the file. it's stuck in some cache somewhere.

**Comment by pjrt** [comment]
@robbyki you are getting this bug? This was fixed a while back. 

Do you mind making a new issue?
