### ISSUE TITLE
Insertion of `verticalMultilineAtDefinitionSiteArityThreshold` broke bincompat

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#1158]
`ScalafmtConfig` is public API, so [this](https://github.com/scalameta/scalafmt/pull/1143/files#diff-f384b64a74c6f7dcb459eaf4c8beb0c4R148) is a binary breaking change, that shipped in a minor version bump (v1.5.0).. 😢

It broke neo-sbt-scalafmt: https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/69

- **Version**: 1.5.1
- **Integration**: neo-sbt-scalafmt
- **Configuration**: irrelevant

## Steps

1. Be a neo-sbt-scalafmt user
2. Upgrade to 1.5.1: `scalafmtVersion := "1.5.1"`

## Problem

```
[error] java.lang.NoSuchMethodError: org.scalafmt.config.ScalafmtConfig.copy$default$23()Ljava/lang/String;
[error] 	at com.lucidchart.scalafmt.impl.Scalafmtter$$anon$1.<init>(Scalafmtter.scala:16)
[error] 	at com.lucidchart.scalafmt.impl.Scalafmtter.formatter(Scalafmtter.scala:14)
[error] 	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$.$anonfun$scalafmtFn$1(ScalafmtCorePlugin.scala:59)
```

## Expectation

Business as usual. (Plugin loads, can format things, assert format, etc)

## Workaround

No direct workaround.

Although other forms of mitigation include: not upgrading, or migrating to `"com.geirsson" % "sbt-scalafmt" % "1.5.1"`.

## Notes

For any readers, @sjrd gave a talk at ScalaSphere 2018 about binary (and source) compatibility: https://twitter.com/sjrdoeraene/status/986351955638398976.

**Comment by dwijnand** [comment]
NB: this fails when calling neo-sbt-scalafmt's `sbt:scalafmt`, either directly (in my case) or automatically on load (in the case of the author of https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/69).

**Comment by olafurpg** [comment]
NB, if you are on sbt 1.0 you might want to try the sbt-scalafmt plugin that is published from this repo, supports format on compile and does not use classloading to invoke scalafmt http://scalameta.org/scalafmt/#sbt

**Comment by dwijnand** [comment]
> if you are on sbt 1.0 you might want to try the sbt-scalafmt plugin

yup! I hope to be able to.

> the `config` package is not protected by binary compatibility

Conventionally, that's really not obvious. 😑
