### ISSUE TITLE
Unable to format Swagger annotated case classes while using verticalMultilineAtDefinitionSite = true

### ISSUE THREAD

**Issue by dwaynepryce** [scalameta/scalafmt#1161]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: Pure CLI
- **Configuration**:
```
newlines.alwaysBeforeTopLevelStatements = true
align.openParenCallSite = false
align.openParenDefnSite = false
spaces.afterKeywordBeforeParen = true
rewrite.rules = [SortImports]
danglingParentheses = true
lineEndings = unix
maxColumn = 160
align = none
includeCurlyBraceInSelectChains = false
binPack.literalArgumentLists = false
runner.optimizer.forceConfigStyleOnOffset = 2
verticalMultilineAtDefinitionSite = true
```

## Steps

Given code like this:
```scala
package com.example

import com.google.common.base.Strings
import io.swagger.annotations.{ApiModel, ApiModelProperty}

import scala.annotation.meta.field

@ApiModel(description = "Metrics for a specific item")
case class ItemMetric(
    @(ApiModelProperty @field)(
      value = "The id being summarized",
      required = true
    )
    id: String,
    @(ApiModelProperty @field)(
      name = "sources",
      value = "The data sources these metrics have been aggregate from",
      required = true
    )
    sources: Seq[String]
) {
  require(
    !Strings.isNullOrEmpty(id),
    "id cannot be null or empty"
  )
  require(
    sources != null && !sources.isEmpty,
    "sources cannot be null or empty"
  )
}
```

When I run scalafmt like this:

```bash
cd src/main/scala/com/example
scalafmt --config ~/source/example/.scalafmt.conf ItemMetric.scala
```

## Problem

Scalafmt formats code like this:
```scala
[warn] Error in /home/dwayne/source/example/src/main/scala/com/example/ItemMetric.scala: org.scalafmt.Error$Incomplete: Unable to format file due to bug in scalafmt
```

## Expectation
The file to be formatted appropriately.

## Workaround

I've found that by removing `verticalMultilineAtDefinitionSite = true` it works without any problems.

## Notes

I've noticed that this is happening in ALL of my swagger model case classes.  However, my swagger rest endpoint annotated akka routes are just fine.  It definitely seems to be the combination of swagger annotations and case classes - but as for why, I have no idea.

**Comment by mads-hartmann** [comment]
@dwaynepryce Can you try 1.5.1? I just tried to create a test to reproduce your example on master and it seems to work fine.

For reference, here's the test case I ran.

```
newlines.alwaysBeforeTopLevelStatements = true
align.openParenCallSite = false
align.openParenDefnSite = false
spaces.afterKeywordBeforeParen = true
rewrite.rules = [SortImports]
danglingParentheses = true
lineEndings = unix
maxColumn = 160
align = none
includeCurlyBraceInSelectChains = false
binPack.literalArgumentLists = false
runner.optimizer.forceConfigStyleOnOffset = 2
verticalMultilineAtDefinitionSite = true
<<< ONLY Work with continuationIndent.defnSite = 2
package com.example

import com.google.common.base.Strings
import io.swagger.annotations.{ApiModel, ApiModelProperty}

import scala.annotation.meta.field

@ApiModel(description = "Metrics for a specific item")
case class ItemMetric(
    @(ApiModelProperty @field)(
      value = "The id being summarized",
      required = true
    )
    id: String,
    @(ApiModelProperty @field)(
      name = "sources",
      value = "The data sources these metrics have been aggregate from",
      required = true
    )
    sources: Seq[String]
) {
  require(
    !Strings.isNullOrEmpty(id),
    "id cannot be null or empty"
  )
  require(
    sources != null && !sources.isEmpty,
    "sources cannot be null or empty"
  )
}
>>>
package com.example

import com.google.common.base.Strings
import io.swagger.annotations.{ApiModel, ApiModelProperty}

import scala.annotation.meta.field

@ApiModel(description = "Metrics for a specific item")
case class ItemMetric(
    @(ApiModelProperty @field)(value = "The id being summarized", required = true)
    id: String,
    @(ApiModelProperty @field)(name = "sources", value = "The data sources these metrics have been aggregate from", required = true)
    sources: Seq[String])
```

**Comment by dwaynepryce** [comment]
@mads-hartmann Just tried 1.5.1, both installed via coursier and through spotlessApply - same problem.  Since you weren't able to repro I assumed I was just crazy and to verify that hypothesis I made this repository: https://github.com/dwaynepryce/scalafmt-example-error

I had another person try it on their workstation and they DID get the same error - and since you weren't able to repro, but we were, I'm going to start tossing out system information:

I'm running Mint 18.3 Sylvia.  The other person was using Ubuntu 17.10.

You can easily test it by cloning that repository and running ./gradlew spotlessApply - though if you are on Windows, you might need gradlew.bat spotlessApply (full disclosure, I never use cmd on Windows for stuff like this, so it might need even more than what I had put together there).  I didn't ask the other person to install scalafmt, but since we both get the same error through spotlessApply AND it's the exact same as when I run "scalafmt" inside the project folder, I'm reasonably confident we have at least two repros.  

The fact that neither of us can get it to work and you can, though, implies it might be system related - or at least that's my intuition.  Let me know if you need any further information or if you are also able to repro off of that example project.  Thanks!

**Comment by dwaynepryce** [comment]
```bash
dwayne@VALINHALL ~/source/example $ ls
build  build.gradle  gradle  gradle.properties  gradlew  gradlew.bat  LICENSE.md  README  src
dwayne@VALINHALL ~/source/example $ cat .scalafmt.conf 
newlines.alwaysBeforeTopLevelStatements = true
align.openParenCallSite = false
align.openParenDefnSite = false
spaces.afterKeywordBeforeParen = true
rewrite.rules = [SortImports]
danglingParentheses = true
lineEndings = unix
maxColumn = 120
align = none
includeCurlyBraceInSelectChains = false
binPack.literalArgumentLists = false
runner.optimizer.forceConfigStyleOnOffset = 2
verticalMultilineAtDefinitionSite = true
dwayne@VALINHALL ~/source/example $ scalafmt
[warn] Error in /home/dwayne/source/example/src/main/scala/com/example/ItemMetric.scala: org.scalafmt.Error$Incomplete: Unable to format file due to bug in scalafmt
dwayne@VALINHALL ~/source/example $ ./gradlew spotlessApply

> Task :spotlessScala FAILED
Step 'scalafmt' found problem in 'src/main/scala/com/example/ItemMetric.scala':
null
java.lang.reflect.InvocationTargetException
        at com.diffplug.spotless.scala.ScalaFmtStep$State.lambda$createFormat$0(ScalaFmtStep.java:121)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.Formatter.applyToAndReturnResultIfDirty(Formatter.java:192)
        at com.diffplug.gradle.spotless.SpotlessTask.applyAnyChanged(SpotlessTask.java:229)
        at com.diffplug.gradle.spotless.SpotlessTask.performAction(SpotlessTask.java:193)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.scalafmt.Error$Incomplete: Unable to format file due to bug in scalafmt
        at org.scalafmt.Scalafmt$.format(Scalafmt.scala:65)
        at org.scalafmt.Scalafmt.format(Scalafmt.scala)
        at com.diffplug.spotless.scala.ScalaFmtStep$State.lambda$createFormat$0(ScalaFmtStep.java:120)
        ... 47 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessScala'.
> java.lang.reflect.InvocationTargetException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

**Comment by mads-hartmann** [comment]
@dwaynepryce Awesome, thanks a lot for this, I'll give it a go and report back :)

**Comment by mads-hartmann** [comment]
@dwaynepryce Alright, I was able to reproduce the problem using your example :)

@olafurpg Any idea why I can't reproduce it when I create a `.source` test file?

**Comment by dwaynepryce** [comment]
@mads-hartmann for what it's worth, I also tried it again by copying back out of the Github issue - my first thought was "oh, maybe some invisible character got lost or something when I copy/pasted into the issue, or when it was rendered back out", but the source file in that repo was generated solely by copy/pasting the code out of this issue anyway.  

I would assume if it were as simple as line endings, it wouldn't be a problem after `lineEndings = unix`, so I wonder now if there's some other platform-problematic character hiding - one that I'm able to pick up in Linux through Firefox, but you via your browser are not?  Or maybe not.  

What I do know is some of this code was written originally in Windows, so CRLF - but again, with `lineEndings = unix`, that should have been purged.  If there are other weird characters coming from Windows, causing problems in Linux, I don't know about them off hand. 

(Sorry for rambling, this just seems like a really weird problem and I don't want to leave any extra information out in case it is useful to you guys)

**Comment by dwaynepryce** [comment]
Drat.  I just tried hand typing the entire class file all over again (pushed it to the sample repository), and I used absolutely NO copy and pasting.  I did this 100% on a Linux system, zero windows involved.  I did, however, allow IntellIj to import the annotations and com.google.common.base.Strings utility - so if some sort of invisible character is sliding into this that causes problems, it would have to be IntelliJ doing it.

I'm running out of time at this exact second to try hand typing absolutely everything straight from vim, but I'll try that next time I come back - that way we can really exhaust this entire train of thought fully.

**Comment by olafurpg** [comment]
Thanks for reporting! I'm able to reproduce from the cli with the latest pre-release
```
$ coursier launch com.geirsson:scalafmt-cli_2.11:1.5.1-22-42d8de3c -r bintray:scalameta/maven -- --stdout item.scala
[warn] Error in /Users/ollie/dev/spire/target/item.scala: org.scalafmt.Error$Incomplete: Unable to format file due to bug in scalafmt
```

Removing `verticalMultilineAtDefinitionSite = true` fixes the problem.

I'm not sure why the `.source` file doesn't reproduce it. What happens in `CliTest` if we add another test like here https://github.com/scalameta/scalafmt/blob/42d8de3c7d7973dc03aa614919e41dd7fdd9aed4/scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala#L330-L347 ?

**Comment by mads-hartmann** [comment]
I'll set up a cli test to see what happens 👍

**Comment by mads-hartmann** [comment]
@olafurpg Added two regression-tests. A cli based one and a normal formatting one.They both pass though (on my mac) 🙃
