### ISSUE TITLE
Invalid fields: trailingCommas

### ISSUE THREAD

**Issue by dbousamra** [scalameta/scalafmt#1217]
This template is a guideline, not a strict requirement.
- **Version**: 1.5.1
- **Integration**: IntelliJ, CLI
- **Configuration**:
```
trailingCommas = always
```

## Steps
Running scalafmt via CLI (installed via brew) or via IntelliJ

## Problem

Scalafmt formats code like this:
```scala
Exception in thread "main" java.lang.IllegalArgumentException: Invalid fields: trailingCommas
        at org.scalafmt.cli.CliOptions$.$anonfun$tryDirectory$2(CliOptions.scala:55)
        at scala.Option$WithFilter.map(Option.scala:146)
        at org.scalafmt.cli.CliOptions$.tryDirectory(CliOptions.scala:49)
        at org.scalafmt.cli.CliOptions$.tryCurrentDirectory(CliOptions.scala:65)
        at org.scalafmt.cli.CliOptions$.auto(CliOptions.scala:34)
        at org.scalafmt.cli.Cli$.$anonfun$getConfig$1(Cli.scala:72)
        at scala.Option.map(Option.scala:146)
        at org.scalafmt.cli.Cli$.getConfig(Cli.scala:72)
        at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:65)
        at org.scalafmt.cli.Cli$.main(Cli.scala:61)
        at org.scalafmt.cli.Cli.main(Cli.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at coursier.Bootstrap.main(Bootstrap.java:428)
```

## Expectation
No errors. It seems a valid configuration option

## Notes

See also..

**Comment by olafurpg** [comment]
Thanks for reporting! This setting was added in v1.6.0-RC1, the docs show the latest master :)

**Comment by jgogstad** [comment]
This is still reported by IntelliJ, scalafmt plugin version 1.5.1

```
12:51	Scalafmt
					Failed to read /Users/jostein.gogstad/development/foo/scalafmt.conf. 
					Invalid fields: trailingCommas
```

scalafmt.conf

```
version = 2.0.0
maxColumn = 120                                
style = defaultWithAlign                       
continuationIndent.defnSite = 2                
align.openParenCallSite = false                
align.openParenDefnSite = false                
continuationIndent.extendSite = 2              
assumeStandardLibraryStripMargin = true        
danglingParentheses = true                     
rewrite.rules = [
  RedundantParens,    
  SortImports,        
  PreferCurlyFors     
]
spaces.inImportCurlyBraces = false             
trailingCommas = never                         
align.tokens.add = [                           
  { code = "shouldBe" }
]
```

Works when `trailingCommas` is removed. IntelliJ reports scalafmt version `2.0.0` under Editor > Code Style > Scala

**Comment by tanishiking** [comment]
@jgogstad 
- As olafurpg said, This setting was added in v1.6.0-RC1.
- intellij scalafmt-plugin version 1.5.1 doesn't have a feature that downloading scalafmt-core specified in your `.scalafmt.conf` (in this case 2.0.0)
  - so you are running scalafmt 1.5.1 instead of 2.0.0
- That's why `trailingCommas` is invalid in your environment

You can enable to run scalafmt by upgrading the plugin :)
I'm sorry I know it's confusing, I'm gonna wrote more about the scalafmt's versioning in this weekend!

**Comment by jgogstad** [comment]
@tanishiking ah, I suspected something like that, thanks. IntelliJ reports using Scalafmt 2.0.0 in the Code style settings, so that was a bit confusing.

I can't see that there is a new release of the IntelliJ plugin though, https://plugins.jetbrains.com/plugin/8236-scalafmt reports that 1.5.1 is latest stable. The [nightly build](https://plugins.jetbrains.com/plugin/8236-scalafmt/versions) has the same RC version as what's depended on by the sbt plugin though.

**Comment by jgogstad** [comment]
An update on this one: It turns out that IntelliJ by itself understands scalafmt 2.0.0 perfectly fine, it's the plugin that's causing problems. Uninstalling the plugin fixed the issue. IntelliJ now correctly picks up the scalafmt config and understands `trailingCommas`.
