### ISSUE TITLE
The cli does not release memory after processing file

### ISSUE THREAD

**Issue by ShaneDelmore** [scalameta/scalafmt#1264]
This template is a guideline, not a strict requirement.
- **Version**: 1.5.1
- **Integration**: cli
- **Configuration**:
```
maxColumn = 100

docstrings = JavaDoc

assumeStandardLibraryStripMargin = false

align = none

continuationIndent.callSite = 2
continuationIndent.defnSite = 2

danglingParentheses = true

spaces.inImportCurlyBraces = false
spaces.afterTripleEquals = true

newlines.sometimesBeforeColonInMethodReturnType = true

binPack.parentConstructors = false
```

## Steps

When I run scalafmt like this:
scalafmt .

## Problem

Scalafmt initially runs fine, but as it gets to about 45% of files formatted, it slows to a crawl, and an hour later is only on 47% formatted.

## Expectation

I would like the formatter to run full speed regardless of the number of files formatted.

## Workaround

If I use xargs to run scalafmt for every visible directory it completes in about an hour.
```
ls -d */ | xargs -I _ scalafmt _
```

## Notes
The xargs workaround works fairly well.  A couple of gotchas for anyone else that tries this:
1.  By default scalafmt processes hidden files as well.  For my use case generated code is kept in the .pants.d directory so it is actually an improvement for my workflow to skip hidden files with the xargs workaround.

2.  Scalafmt throws a stack trace if there are no files to format, so the trivial xargs workaround shown will output an error for every directory passed to it that contains no scala files but will continue processing so this is a nuisance only.
```
Exception in thread "main" org.scalafmt.Error$NoMatchingFiles$: No files formatted/tested. Verify include/exclude filters and command line arguments.
	at org.scalafmt.Error$NoMatchingFiles$.<clinit>(Error.scala)
	at org.scalafmt.cli.Cli$.run(Cli.scala:158)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:66)
	at org.scalafmt.cli.Cli$.main(Cli.scala:61)
	at org.scalafmt.cli.Cli.main(Cli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coursier.Bootstrap.main(Bootstrap.java:430)
```

**Comment by ShaneDelmore** [comment]
Interestingly, I am able to complete formatting my whole repo using the graal native version of scalafmt-cli.  It is slower, but does run to completion.

**Comment by kitbellew** [comment]
please reopen if this is still reproducible. couldn't repro myself.
