### ISSUE TITLE
GraalVM native-image gives errors with version=1.5.1

### ISSUE THREAD

**Issue by hugo-vrijswijk** [scalameta/scalafmt#1394]
- **Version**: 2.0.0-RC5 (and latest snapshot)
- **Integration**: cli
- **Configuration**:
```
version = 1.5.1
```

## Steps

Building scalafmt native-image and running it like this on a project with `version = 1.5.1`:
```bash
CLASSPATH=$(coursier fetch org.scalameta:scalafmt-cli_2.12:2.0.0-RC5 | paste -s -d: -)
native-image -cp $CLASSPATH org.scalafmt.cli.Cli
./org.scalafmt.cli.cli
```
Gives a lot of error output:
```log
org.scalafmt.cli.FailedToFormat: [redacted]/.scalafmt.conf
Caused by: java.lang.RuntimeException: failed to resolve Scalafmt version '1.5.1'
        at org.scalafmt.interfaces.ScalafmtReporter.error(ScalafmtReporter.java:37)
        at org.scalafmt.cli.ScalafmtCliReporter.error(ScalafmtCliReporter.scala:13)
        at org.scalafmt.dynamic.ScalafmtDynamic.reportError(ScalafmtDynamic.scala:81)
        at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:64)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.handleFile(ScalafmtDynamicRunner.scala:84)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$3(ScalafmtDynamicRunner.scala:50)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$3$adapted(ScalafmtDynamicRunner.scala:45)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.run(ScalafmtDynamicRunner.scala:45)
        at org.scalafmt.cli.Cli$.run(Cli.scala:95)
        at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:66)
        at org.scalafmt.cli.Cli$.main(Cli.scala:55)
        at org.scalafmt.cli.Cli.main(Cli.scala)
Caused by: java.util.concurrent.ExecutionException: Boxed Error
        at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
        at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
        at scala.concurrent.Promise.complete(Promise.scala:53)
        at scala.concurrent.Promise.complete$(Promise.scala:52)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
        at scala.concurrent.Promise.failure(Promise.scala:104)
        at scala.concurrent.Promise.failure$(Promise.scala:104)
        at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:187)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:45)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl not found
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:200)
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
        at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:277)
        at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
        at scala.xml.factory.XMLLoader.parser(XMLLoader.scala:28)
        at scala.xml.factory.XMLLoader.parser$(XMLLoader.scala:27)
        at scala.xml.XML$.parser(XML.scala:58)
        at scala.xml.factory.XMLLoader.loadString(XMLLoader.scala:60)
        at scala.xml.factory.XMLLoader.loadString$(XMLLoader.scala:60)
        at scala.xml.XML$.loadString(XML.scala:58)
        at com.geirsson.shaded.coursier.core.compatibility.package$.parse$1(package.scala:35)
        at com.geirsson.shaded.coursier.core.compatibility.package$.xmlParse(package.scala:68)
        at com.geirsson.shaded.coursier.maven.MavenRepository.parseRawPom$1(MavenRepository.scala:314)
        at com.geirsson.shaded.coursier.maven.MavenRepository.$anonfun$findVersioning$7(MavenRepository.scala:372)
        at com.geirsson.shaded.coursier.util.EitherT.$anonfun$flatMap$1(EitherT.scala:16)
        at com.geirsson.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:10)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
        at java.lang.Class.forName(DynamicHub.java:1083)
        at javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:124)
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:188)
        ... 25 more
```

Above output is done a lot (once per file?)

Running without native-image works fine: 

```bash
coursier launch org.scalameta:scalafmt-cli_2.12:2.0.0-RC5
```

Running with `version = 2.0.0-RC5` or without the configuration also works fine

**Comment by borissmidt** [comment]
If i can recall correctly, scalafrmt 2.0.0 does dynamic class loading which probably gives you problems witht the native image.
Also graal native doesn't suport some parts of java 8. (invokedynamic). Which is used by scala 2.12 lambdas. 

https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md

**Comment by hugo-vrijswijk** [comment]
Thanks for the explanation @borissmidt ! After trying out a bit more, the error seems to come from a difference in the scalafmt and config version. Probably where the dynamic classloading comes in, like you said. I guess that makes this error a bit out of scope, so I'll close this issue

**Comment by olafurpg** [comment]
It should be possible to keep a main function that doesn't use reflection to allow native images. We'll need this either way once Scala Native supports is out, which should be soon now that @ekrich has ported typesafe/config to Scala.
