### ISSUE TITLE
"key not found" with includeNoParensInSelectChains = true

### ISSUE THREAD

**Issue by elijahsmith** [scalameta/scalafmt#1407]
- **Version**: 2.0.0-RC6
- **Integration**: sbt, cli
- **Configuration**:
```
style = default
version=2.0.0-RC6
project.git = true
includeNoParensInSelectChains = true
```

## Steps

Given code like this:
```scala
package com.foo.bar.api.controllers.admin

import play.api.http.{ContentTypeOf, ContentTypes, Writeable}

object CirceWritable {
  implicit def contentTypeOf_CirceJson(): ContentTypeOf[io.circe.Json] =
    ContentTypeOf[io.circe.Json](Some(ContentTypes.JSON))
}
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

I get a stacktrace that looks like this (in this file, and many others):
```
org.scalafmt.cli.FailedToFormat: /Users/elijahsmith/apollo/pikachu/src/main/scala/com/apolloagriculture/pikachu/services/sms/SMSClient.scala
Caused by: java.util.NoSuchElementException: key not found: 5350276406439838429
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:63)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:63)
	at org.scalafmt.internal.FormatOps.getSelectsLastToken(FormatOps.scala:484)
	at org.scalafmt.internal.FormatOps.chainOptimalToken(FormatOps.scala:503)
	at org.scalafmt.internal.Router.getSplits(Router.scala:976)
	at org.scalafmt.internal.Router.$anonfun$getSplitsMemo$1(Router.scala:1488)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at org.scalafmt.internal.Router.getSplitsMemo(Router.scala:1487)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$routes$1(BestFirstSearch.scala:41)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.scalafmt.internal.BestFirstSearch.<init>(BestFirstSearch.scala:40)
	at org.scalafmt.Scalafmt$.format(Scalafmt.scala:62)
	at org.scalafmt.Scalafmt.format(Scalafmt.scala)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scalafmt.dynamic.ScalafmtReflect.format(ScalafmtReflect.scala:104)
	at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$tryFormat$1(ScalafmtDynamic.scala:213)
	at scala.util.Try$.apply(Try.scala:213)
	at org.scalafmt.dynamic.ScalafmtDynamic.tryFormat(ScalafmtDynamic.scala:201)
	at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$formatDetailed$1(ScalafmtDynamic.scala:99)
	at scala.util.Either.flatMap(Either.scala:341)
	at org.scalafmt.dynamic.ScalafmtDynamic.formatDetailed(ScalafmtDynamic.scala:98)
	at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:60)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.handleFile(ScalafmtDynamicRunner.scala:84)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$3(ScalafmtDynamicRunner.scala:50)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$3$adapted(ScalafmtDynamicRunner.scala:45)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.run(ScalafmtDynamicRunner.scala:45)
	at org.scalafmt.cli.Cli$.run(Cli.scala:95)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:66)
	at org.scalafmt.cli.Cli$.main(Cli.scala:55)
	at org.scalafmt.cli.Cli.main(Cli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coursier.bootstrap.Bootstrap.main(Unknown Source)
```

## Expectation

No stack trace ;)

**Comment by To-om** [comment]
I don't know why by scalafmt doesn't like full qualified class name. If you replace `io.circe.Json` by `Json` and add an import, it works.

**Comment by poslegm** [comment]
@elijahsmith please try it with scalafmt [2.0.0-RC8](https://github.com/scalameta/scalafmt/releases/tag/v2.0.0-RC8)

**Comment by elijahsmith** [comment]
this is no longer happening... thanks folks!
