### ISSUE TITLE
2.1.0 not pushed to maven repo?

### ISSUE THREAD

**Issue by CB-andrewehrlich** [scalameta/scalafmt#1519]
```
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.scalameta:sbt-scalafmt:2.1.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalameta:sbt-scalafmt;sbtVersion=1.0;scalaVersion=2.12:2.1.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.1.0/sbt-scalafmt-2.1.0.pom
[error]   not found: /Users/andrew.ehrlich/.ivy2/local/org.scalameta/sbt-scalafmt/scala_2.12/sbt_1.0/2.1.0/ivys/ivy.xml
[error]   not found: https://oss.sonatype.org/content/repositories/releases/org/scalameta/sbt-scalafmt_2.12_1.0/2.1.0/sbt-scalafmt-2.1.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalameta/sbt-scalafmt/scala_2.12/sbt_1.0/2.1.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scalameta/sbt-scalafmt/scala_2.12/sbt_1.0/2.1.0/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2909)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:289)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:sbt-scalafmt;sbtVersion=1.0;scalaVersion=2.12:2.1.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.1.0/sbt-scalafmt-2.1.0.pom
[error]   not found: /Users/andrew.ehrlich/.ivy2/local/org.scalameta/sbt-scalafmt/scala_2.12/sbt_1.0/2.1.0/ivys/ivy.xml
[error]   not found: https://oss.sonatype.org/content/repositories/releases/org/scalameta/sbt-scalafmt_2.12_1.0/2.1.0/sbt-scalafmt-2.1.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalameta/sbt-scalafmt/scala_2.12/sbt_1.0/2.1.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scalameta/sbt-scalafmt/scala_2.12/sbt_1.0/2.1.0/ivys/ivy.xml
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by poslegm** [comment]
`scalafmt` and `sbt-scalafmt` plugin has independent versioning schemes. Actual version for sbt plugin is 2.0.6 (you can read about plugin versioning [here](https://github.com/scalameta/sbt-scalafmt/releases/tag/v2.0.0)).

Just specify the scalafmt version you want in your `.scalafmt.conf`:

```
version = 2.1.0
align = none
...
```

**Comment by tanishiking** [comment]
Sorry for the confusion, https://github.com/scalameta/scalafmt/issues/1519#issuecomment-539436006 @poslegm is right.
Thank you for using scalafmt! @CB-andrewehrlich

**Comment by CB-andrewehrlich** [comment]
Got it, thanks!
