### ISSUE TITLE
NullPointerException when using Scalafmt.withMavenRepositories from Gradle

### ISSUE THREAD

**Issue by augi** [scalameta/scalafmt#1618]
In `gradle-scalafmt`, [we started](https://github.com/alenkacz/gradle-scalafmt/commit/2e597163ea2fadd3a3fa5af0fa00ff76992b86a9) using `withMavenRepositories` method when configuring `Scalafmt`. Unfortunately, the build then sometimes (esp. in clean environment, without anything cached) fails with following error:
```
  Caused by: java.lang.NullPointerException: Username must not be null!
  	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:910)
  	at org.gradle.internal.resource.transport.http.ntlm.NTLMCredentials.<init>(NTLMCredentials.java:36)
  	at org.gradle.internal.resource.transport.http.HttpClientConfigurer.useCredentials(HttpClientConfigurer.java:197)
  	at org.gradle.internal.resource.transport.http.HttpClientConfigurer.configureCredentials(HttpClientConfigurer.java:139)
  	at org.gradle.internal.resource.transport.http.HttpClientConfigurer.configure(HttpClientConfigurer.java:109)
  	at org.gradle.internal.resource.transport.http.HttpClientHelper.getClient(HttpClientHelper.java:195)
```

Also a user of `gradle-scalafmt` [reported](https://github.com/alenkacz/gradle-scalafmt/issues/32) this as an issue.

It seems that this happens only if `scalafmt` is executed before `scalaCompile`. If `scalaCompile` goes first then it correctly download all dependencies (to the cache) and `scalafmt` goes well then as well.

Maybe it is a bug in coursier that is used under the hood?

**Comment by olafurpg** [comment]
Thank you for reporting! The stack trace doesn’t point to scalafmt, can you please include what Scalafmt method is failing?

**Comment by augi** [comment]
Sorry for bothering you with this. It seems that it was a strange error in `gradle-scalafmt`. I don't know why but [this change](https://github.com/alenkacz/gradle-scalafmt/commit/23dcc6ba7098e93186afb4226e1b5bf80e34c1f5) to make the code more Groovish apparently fixed the issue.
