### ISSUE TITLE
Error formatting type

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalafmt#1720]
This template is a guideline, not a strict requirement.
- **Version**: 2.4.1 (2.3.2 did not cause the error)
- **Integration**: Command Line
- **Configuration**:
```
version = 2.4.1
style = defaultWithAlign
docstrings = JavaDoc
assumeStandardLibraryStripMargin = true
project.excludeFilters = [
  scalalib/
]
project.git = true
# changed 1.6 or after
align.openParenCallSite = true
align.openParenDefnSite = true
# avoid wrapping parens on new line
danglingParentheses.defnSite = false
danglingParentheses.callSite = false
# leave literals alone
literals.long = unchanged
literals.float = unchanged
literals.double = unchanged
```

## Steps

When running `$ scripts/scalafmt unit-tests/src/test/scala/scala/scalanative/unsafe/TagSuite.scala`
Given code like this:
```scala
 type iovec = CStruct2[Ptr[Byte], // iov_base
                        CSize] // iov_len
```

## Problem
Scalafmt errors
```scala
org.scalafmt.cli.FailedToFormat: /Users/eric/workspace/scala-native/unit-tests/src/test/scala/scala/scalanative/unsafe/TagSuite.scala
Caused by: org.scalafmt.Error$PreciseIncomplete: /Users/eric/workspace/scala-native/unit-tests/src/test/scala/scala/scalanative/unsafe/TagSuite.scala:144: error: Unable to format file due to bug in scalafmt
  type iovec = CStruct2[Ptr[Byte], // iov_base
                                   ^
	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:86)
	at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:87)
	at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:66)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3(ScalafmtCoreRunner.scala:44)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3$adapted(ScalafmtCoreRunner.scala:43)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```
Scalafmt formats code like this:
```scala
No code change
```

## Expectation

No errors.

I would like the formatted output to look like this:
```Scala
type iovec = CStruct2[Ptr[Byte], // iov_base
                      CSize]     // iov_len
```

## Workaround

I've found that by writing the code like this the error goes away but no formatting occurs.
```Scala
type iovec = CStruct2[Ptr[Byte], // iov_base
                      CSize     // iov_len
]
Edit: this is not really a workaround but may hint at the problem.
```

**Comment by ekrich** [comment]
Could be somewhat related to this feature.
https://github.com/scalameta/scalafmt/issues/1249

**Comment by poslegm** [comment]
Minimal config for reproduce:

```
version = 2.0.0-RC1
```

Version 1.5.1 formats code without errors:

```
type iovec = CStruct2[Ptr[Byte], // iov_base
                      CSize]     // iov_len
```

**Comment by ekrich** [comment]
Thanks for fixing this 😄
