### ISSUE TITLE
wrong binary in 2.4.2 release?

### ISSUE THREAD

**Issue by ornicar** [scalameta/scalafmt#1769]
https://github.com/scalameta/scalafmt/releases/download/v2.4.2/scalafmt-linux.zip

```
./scalafmt --version
scalafmt 2.4.1+33-b35acafc-SNAPSHOT`
```

And therefore it can't format projects where `version="2.4.2"`:

```
error: invalid Scalafmt version.

This Scalafmt installation has version '2.4.1+33-b35acafc-SNAPSHOT' and the version configured in '/home/thib/lila-fishnet/.scalafmt.conf' is '2.4.2'.
To fix this problem, add the following line to .scalafmt.conf:

version = '2.4.1+33-b35acafc-SNAPSHOT'

NOTE: this error happens only when running a native Scalafmt binary.
Scalafmt automatically installs and invokes the correct version of Scalafmt when running on the JVM.
```

**Comment by poslegm** [comment]
Thank you for reporting. The issue may be in not running CI on tag push. I tried to fix it [here](https://github.com/scalameta/scalafmt/commit/33c33f49fc9ddbcba8db7b11a40dc9339c59c2f2), will look at the next release.

Current workaround is non-native images from [coursier](https://github.com/scalameta/scalafmt/commit/33c33f49fc9ddbcba8db7b11a40dc9339c59c2f2).

**Comment by lbialy** [comment]
I guess much bigger issue is that this binary is completely broken:
```
org.scalafmt.cli.FailedToFormat: /home/lbialy/Projects/x/y/z/src/main/scala/com/whatever/configuration.scala
Caused by: java.lang.NoSuchMethodException: org.scalafmt.internal.FormatWriter$$anon$2.last()
        at java.lang.Class.getMethod(DynamicHub.java:1053)
        at org.scalafmt.internal.FormatWriter.reflMethod$Method1(FormatWriter.scala:564)
        at org.scalafmt.internal.FormatWriter.alignmentTokens(FormatWriter.scala:564)
        at org.scalafmt.internal.FormatWriter$FormatLocations.<init>(FormatWriter.scala:258)
        at org.scalafmt.internal.FormatWriter.getFormatLocations(FormatWriter.scala:154)
        at org.scalafmt.internal.FormatWriter.mkString(FormatWriter.scala:26)
        at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:73)
        at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:87)
        at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:66)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3(ScalafmtCoreRunner.scala:44)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3$adapted(ScalafmtCoreRunner.scala:43)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1274)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:946)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:943)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:169)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

It would be beneficial to run native-image-agent alongside tests to generate proper native-image configuration for generation of binary.

**Comment by lbialy** [comment]
Last working binary was for 2.3.2. Also structure of dist zipfile changed after 2.3.2, directory is no longer inside of the zip and therefore native binary installation script is also broken.

**Comment by bsolomon1124** [comment]
I confirmed that 2.3.2 is the last working release; 2.4.1 throws the same exception.  (And the 2.4.0 release has no scalafmt-linux.zip asset.)  And yes, as @lbialy points out, with 2.3.2 the `install-scalafmt-native.sh` needs an extra `cd` into the toplevel directory after unzipping (or a flag to `unzip`).

**Comment by poslegm** [comment]
Binary from latest 2.5.0-RC1 release works well:

```
~ VERSION=2.5.0-RC1
INSTALL_LOCATION=/usr/local/bin/scalafmt-native
curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | \
  sh -s -- $VERSION $INSTALL_LOCATION
scalafmt-native --version
scalafmt 2.5.0-RC1
```
