### ISSUE TITLE
Scalafmt errors on formatting simple file

### ISSUE THREAD

**Issue by GUIpsp** [scalameta/scalafmt#1937]
This template is a guideline, not a strict requirement.
- **Version**: 2.5
- **Integration**: CLI
- **Configuration**: Default

## Steps

Given code like this:
```scala
object Record1 {
  def Record1(): () = {
  }
  def main(args: Array[String]): () = {
    new Thread(()=>{Record1()})
  }
}
```

When I run scalafmt like this:

```bash
scalafmt Record1.scala
```

## Problem

scalafmt fails to format with the following error
```
Caused by: org.scalameta.UnreachableError: this code path should've been unreachable
	at org.scalameta.UnreachableError$.raise(package.scala:40)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$makeTupleType$2(ScalametaParser.scala:827)
	at scala.meta.internal.parsers.ScalametaParser.makeTuple(ScalametaParser.scala:802)
	at scala.meta.internal.parsers.ScalametaParser.makeTupleType(ScalametaParser.scala:827)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$tupleInfixType$7(ScalametaParser.scala:945)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$tupleInfixType$1(ScalametaParser.scala:945)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.tupleInfixType(ScalametaParser.scala:859)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$typRest$1(ScalametaParser.scala:984)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typRest(ScalametaParser.scala:979)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typRest$(ScalametaParser.scala:978)
	at scala.meta.internal.parsers.ScalametaParser$outPattern$.typRest(ScalametaParser.scala:2454)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$typ$1(ScalametaParser.scala:974)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typ(ScalametaParser.scala:965)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typ$(ScalametaParser.scala:964)
	at scala.meta.internal.parsers.ScalametaParser$outPattern$.typ(ScalametaParser.scala:2454)
	at scala.meta.internal.parsers.ScalametaParser.typ(ScalametaParser.scala:2475)
	at scala.meta.internal.parsers.ScalametaParser.typedOpt(ScalametaParser.scala:1463)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$funDefRest$2(ScalametaParser.scala:3001)
	at scala.meta.internal.parsers.ScalametaParser.fromWithinReturnType(ScalametaParser.scala:411)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$funDefRest$1(ScalametaParser.scala:3001)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.funDefRest(ScalametaParser.scala:2987)
	at scala.meta.internal.parsers.ScalametaParser.funDefOrDclOrSecondaryCtor(ScalametaParser.scala:2983)
	at scala.meta.internal.parsers.ScalametaParser.defOrDclOrSecondaryCtor(ScalametaParser.scala:2936)
	at scala.meta.internal.parsers.ScalametaParser.nonLocalDefOrDcl(ScalametaParser.scala:2924)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:3495)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:3491)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:3442)
	at scala.meta.internal.parsers.ScalametaParser.templateStats(ScalametaParser.scala:3490)
	at scala.meta.internal.parsers.ScalametaParser.templateStatSeq(ScalametaParser.scala:3487)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateBody$1(ScalametaParser.scala:3359)
	at scala.meta.internal.parsers.ScalametaParser.inBraces(ScalametaParser.scala:327)
	at scala.meta.internal.parsers.ScalametaParser.templateBody(ScalametaParser.scala:3359)
	at scala.meta.internal.parsers.ScalametaParser.templateBodyOpt(ScalametaParser.scala:3364)
	at scala.meta.internal.parsers.ScalametaParser.templateOpt(ScalametaParser.scala:3353)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$objectDef$1(ScalametaParser.scala:3131)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.objectDef(ScalametaParser.scala:3126)
	at scala.meta.internal.parsers.ScalametaParser.tmplDef(ScalametaParser.scala:3076)
	at scala.meta.internal.parsers.ScalametaParser.topLevelTmplDef(ScalametaParser.scala:3062)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$topStat$1.applyOrElse(ScalametaParser.scala:3461)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$topStat$1.applyOrElse(ScalametaParser.scala:3451)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:3442)
	at scala.meta.internal.parsers.ScalametaParser.topStatSeq(ScalametaParser.scala:3450)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:3646)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
	at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:3612)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:3595)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
	at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:3594)
	at scala.meta.internal.parsers.ScalametaParser.entrypointSource(ScalametaParser.scala:3600)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$2(ScalametaParser.scala:128)
	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:38)
	at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:128)
	at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
	at scala.meta.internal.parsers.ScalametaParser$$anon$190.apply(ScalametaParser.scala:3656)
	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
	at org.scalafmt.rewrite.Rewrite$.apply(Rewrite.scala:153)
	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:71)
	at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:91)
	at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:70)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:46)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:45)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by GUIpsp** [comment]
Ignore this issue for now, the code I have is mis-generated

**Comment by GUIpsp** [comment]
Turns out this issue was false, caused by an issue with my code. Closing
