### ISSUE TITLE
org.scalafmt.cli.FailedToFormat

### ISSUE THREAD

**Issue by hepin1989** [scalameta/scalafmt#1950]
scalafmt version: 2.5.1, graal-native image for macos
configuration: 2.5.1, changed manually at akka/akka
codes: akka/akka master

```
run scalafmt at akka/akka
```
got
```
IndentOperator: top-level presets deprecated; use 'preset' subsection
DanglingParentheses: top-level presets deprecated; use 'preset' subsection
org.scalafmt.cli.FailedToFormat: /Users/kerr/IdeaProjects/akka/akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphPartitionSpec.scalarmatted
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded on '3∙,[898:899]', line 29
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:189)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$2(BestFirstSearch.scala:209)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:195)
	at org.scalafmt.internal.BestFirstSearch.run$1(BestFirstSearch.scala:304)
	at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:305)
	at org.scalafmt.internal.BestFirstSearch$.apply(BestFirstSearch.scala:347)
	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:76)
	at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:91)
	at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:70)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:46)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:45)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1274)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:946)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:943)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:159)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
/Users/kerr/IdeaProjects/akka/scripts/authors.scala:1: error: expected class or object definition
#!/bin/sh[#######   ] 1685 source files formatted
^
org.scalafmt.cli.FailedToFormat: /Users/kerr/IdeaProjects/akka/akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded on '{∙env[13409:13421]', line 330
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:189)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$2(BestFirstSearch.scala:209)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:195)
	at org.scalafmt.internal.BestFirstSearch.shortestPathMemo(BestFirstSearch.scala:111)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:179)
	at org.scalafmt.internal.BestFirstSearch.run$1(BestFirstSearch.scala:304)
	at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:305)
	at org.scalafmt.internal.BestFirstSearch$.apply(BestFirstSearch.scala:347)
	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:76)
	at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:91)
	at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:70)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:46)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:45)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1274)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:946)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:943)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:169)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
org.scalafmt.cli.FailedToFormat: /Users/kerr/IdeaProjects/akka/akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded on '=>∙message[44738:44760]', line 1193
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:189)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$2(BestFirstSearch.scala:209)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:195)
	at org.scalafmt.internal.BestFirstSearch.run$1(BestFirstSearch.scala:304)
	at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:305)
	at org.scalafmt.internal.BestFirstSearch$.apply(BestFirstSearch.scala:347)
	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:76)
	at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:91)
	at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:70)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:46)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:45)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1274)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:946)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:943)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:169)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by kitbellew** [comment]
Can you please use the requested template? What is your configuration now? What version did you use before, which didn't have this error, and what was the configuration then?

Your source is pretty large, you might need to increase runner limits.
