### ISSUE TITLE
crash for some very simple code (StringIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by mberndt123** [scalameta/scalafmt#2032]
Hi,

scalafmt 2.6 crashes when you feed it the following code:
```scala
object Foo {
  s"""${print(before, "before")}
     |${print(after, "after")}""".stripMargin
}
```

I'm using a very simple configuration:
```
version = "2.6.0"
preset = default
```
The error message is this:
```
org.scalafmt.cli.FailedToFormat: /tmp/blub.scala
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at scala.collection.StringOps$.apply$extension(StringOps.scala:170)
        at org.scalafmt.internal.FormatWriter$FormatLocations$Entry.$anonfun$formatMarginized$4(FormatWriter.scala:367)
        at org.scalafmt.internal.FormatWriter$FormatLocations$Entry.$anonfun$formatMarginized$4$adapted(FormatWriter.scala:360)
        at scala.Option.map(Option.scala:242)
        at org.scalafmt.internal.FormatWriter$FormatLocations$Entry.$anonfun$formatMarginized$3(FormatWriter.scala:360)
        at scala.Option.flatMap(Option.scala:283)
        at org.scalafmt.internal.FormatWriter$FormatLocations$Entry.formatMarginized(FormatWriter.scala:359)
        at org.scalafmt.internal.FormatWriter.$anonfun$mkString$1(FormatWriter.scala:59)
        at org.scalafmt.internal.FormatWriter.$anonfun$mkString$1$adapted(FormatWriter.scala:45)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
        at org.scalafmt.internal.FormatWriter.mkString(FormatWriter.scala:45)
        at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:77)
        at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:91)
        at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:70)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:46)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:45)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:946)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:943)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by kitbellew** [comment]
Fixed in #2029.
