### ISSUE TITLE
IntelliJ scalafmt plugin throws `java.lang.IllegalArgumentException: transpose requires all collections have the same size`

### ISSUE THREAD

**Issue by dope9967** [scalameta/scalafmt#2144]
- **Version**: 1.5.1
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.3.2
docstrings = ScalaDoc
align = more
maxColumn = 120
assumeStandardLibraryStripMargin = true
lineEndings=preserve
```

IntelliJ 2020.2 keeps reporting that scalafmt plugin throws the following error when formatting files. Started to happen after updating to 2020.2, not sure how to troubleshoot it.

```
java.lang.IllegalArgumentException: transpose requires all collections have the same size
	at scala.collection.generic.GenericTraversableTemplate.fail$1(GenericTraversableTemplate.scala:213)
	at scala.collection.generic.GenericTraversableTemplate.$anonfun$transpose$2(GenericTraversableTemplate.scala:225)
	at scala.collection.generic.GenericTraversableTemplate.$anonfun$transpose$2$adapted(GenericTraversableTemplate.scala:217)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.generic.GenericTraversableTemplate.transpose(GenericTraversableTemplate.scala:217)
	at scala.collection.generic.GenericTraversableTemplate.transpose$(GenericTraversableTemplate.scala:209)
	at scala.collection.AbstractTraversable.transpose(Traversable.scala:104)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl.lubParamTpes$1(ExpectedTypesImpl.scala:207)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl.expectedFunctionTypeFromOverloadedAlternatives(ExpectedTypesImpl.scala:230)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl.filterAlternatives(ExpectedTypesImpl.scala:87)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl.expectedExprType(ExpectedTypesImpl.scala:67)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.expectedTypeEx$extension(ScExpression.scala:176)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.expectedType$extension(ScExpression.scala:173)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$getContextInfo$3(ReferenceExpressionResolver.scala:65)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$resolveWithName$1(ReferenceExpressionResolver.scala:136)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.checkFunction$1(MethodResolveProcessor.scala:331)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.problemsFor(MethodResolveProcessor.scala:461)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.checkResultsApplicability(MethodResolveProcessor.scala:758)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.candidates(MethodResolveProcessor.scala:583)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.collectCandidates(MethodResolveProcessor.scala:167)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.candidatesS(MethodResolveProcessor.scala:138)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver$$anon$1.candidatesS(ReferenceExpressionResolver.scala:145)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.processType$1(ReferenceExpressionResolver.scala:540)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.processTypes$1(ReferenceExpressionResolver.scala:509)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.doResolve(ReferenceExpressionResolver.scala:602)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolveWithName(ReferenceExpressionResolver.scala:196)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$resolve$1(ReferenceExpressionResolver.scala:107)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolve(ReferenceExpressionResolver.scala:124)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.liftedTree2$1(ScReferenceExpressionImpl.scala:556)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.shapeResolveImpl(ScReferenceExpressionImpl.scala:554)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.$anonfun$shapeResolve$1(ScReferenceExpressionImpl.scala:69)
	at scala.Option.fold(Option.scala:158)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.shapeResolve(ScReferenceExpressionImpl.scala:70)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver$$anon$1.candidatesS(ReferenceExpressionResolver.scala:147)
	at org.jetbrains.plugins.scala.lang.resolve.processor.BaseProcessor.candidates(BaseProcessor.scala:78)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.smartResolve$1(ReferenceExpressionResolver.scala:156)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolveWithName(ReferenceExpressionResolver.scala:198)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$resolve$1(ReferenceExpressionResolver.scala:107)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolve(ReferenceExpressionResolver.scala:124)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.liftedTree1$1(ScReferenceExpressionImpl.scala:552)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveImpl(ScReferenceExpressionImpl.scala:550)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.$anonfun$multiResolveScala$1(ScReferenceExpressionImpl.scala:63)
	at scala.Option.fold(Option.scala:158)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveScala(ScReferenceExpressionImpl.scala:64)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceImpl.bind(ScReferenceImpl.scala:44)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScUnderscoreSectionImpl.innerType(ScUnderscoreSectionImpl.scala:38)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.liftedTree4$1(ScExpression.scala:197)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getNonValueType$extension(ScExpression.scala:190)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.liftedTree5$1(ScExpression.scala:232)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getTypeWithoutImplicits$extension(ScExpression.scala:221)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.liftedTree1$1(ScExpression.scala:138)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.getTypeAfterImplicitConversion(ScExpression.scala:119)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.getTypeAfterImplicitConversion$(ScExpression.scala:119)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScExpressionImplBase.getTypeAfterImplicitConversion(ScExpressionImplBase.scala:11)
	at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.doNoNamed$1(Compatibility.scala:333)
	at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.checkConformanceExt(Compatibility.scala:445)
	at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.checkParameterListConformance$1(Compatibility.scala:537)
	at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.compatible(Compatibility.scala:567)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.checkSimpleApplication$1(MethodResolveProcessor.scala:411)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.problemsFor(MethodResolveProcessor.scala:467)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.checkResultsApplicability(MethodResolveProcessor.scala:758)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.candidates(MethodResolveProcessor.scala:583)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.collectCandidates(MethodResolveProcessor.scala:164)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.candidatesS(MethodResolveProcessor.scala:138)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver$$anon$1.candidatesS(ReferenceExpressionResolver.scala:151)
	at org.jetbrains.plugins.scala.lang.resolve.processor.BaseProcessor.candidates(BaseProcessor.scala:78)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.smartResolve$1(ReferenceExpressionResolver.scala:156)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolveWithName(ReferenceExpressionResolver.scala:198)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$resolve$1(ReferenceExpressionResolver.scala:107)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolve(ReferenceExpressionResolver.scala:124)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.liftedTree1$1(ScReferenceExpressionImpl.scala:552)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveImpl(ScReferenceExpressionImpl.scala:550)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.$anonfun$multiResolveScala$1(ScReferenceExpressionImpl.scala:63)
	at scala.Option.fold(Option.scala:158)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveScala(ScReferenceExpressionImpl.scala:64)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceImpl.bind(ScReferenceImpl.scala:44)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.innerType(ScReferenceExpressionImpl.scala:176)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.liftedTree4$1(ScExpression.scala:197)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getNonValueType$extension(ScExpression.scala:190)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.tryToGetInnerTypeExt(MethodInvocationImpl.scala:88)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.innerTypeExt$macro$111$$cachedFun$1(MethodInvocationImpl.scala:69)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.innerTypeExt(MethodInvocationImpl.scala:67)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.applyOrUpdateElement(MethodInvocationImpl.scala:62)
	at org.jetbrains.plugins.scala.codeInsight.hints.ScalaInlayParameterHintsProvider$ResolveMethodCall$.unapply(ScalaInlayParameterHintsProvider.scala:124)
	at org.jetbrains.plugins.scala.codeInsight.hints.ScalaInlayParameterHintsProvider.getParameterHints(ScalaInlayParameterHintsProvider.scala:29)
	at com.intellij.codeInsight.hints.InlayParameterHintsProvider.getParameterHints(InlayParameterHintsProvider.java:29)
	at org.jetbrains.plugins.scala.codeInsight.hints.ScalaInlayParameterHintsProvider.getParameterHints(ScalaInlayParameterHintsProvider.scala:22)
	at com.intellij.codeInsight.hints.ParameterHintsPass.process(ParameterHintsPass.java:74)
	at com.intellij.codeInsight.hints.ParameterHintsPass.lambda$doCollectInformation$0(ParameterHintsPass.java:66)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:66)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by dope9967** [comment]
Seems to have stopped happening after IntelliJ Scala Plugin update https://plugins.jetbrains.com/plugin/1347-scala/versions/stable/94423.
