### ISSUE TITLE
Search state exploded on Scala-Native

### ISSUE THREAD

**Issue by catap** [scalameta/scalafmt#2299]
Scala-Native uses scalafmt to keep its code well formated and one (very complex) file can't be parsed because of errro:
```
org.scalafmt.cli.FailedToFormat: /Users/catap/src/scala-native/nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenExpr.scala
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded around line 1711
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:186)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6(BestFirstSearch.scala:215)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6$adapted(BestFirstSearch.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:202)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6(BestFirstSearch.scala:215)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$6$adapted(BestFirstSearch.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:305)
```

The easy way to reproduce it:
1. `git clone https://github.com/scala-native/scala-native.git`
2. `./scripts/scalafmt`

**Comment by kitbellew** [comment]
try increasing `runner.optimizer.maxVisitsPerToken` from default 10000.

**Comment by catap** [comment]
It works, thanks
