### ISSUE TITLE
Specifying files in stdin via @- not working

### ISSUE THREAD

**Issue by mrubin** [scalameta/scalafmt#2342]
Invoking scalafmt 2.7.5 on Mac as follows:

```
echo "foo" | scalafmt @-
```
I would expect scalafmt to run as if executed like `scalafmt foo`. However, what I see is the following:

```
Exception in thread "main" java.nio.file.NoSuchFileException: /Users/redacted/@-
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.nio.file.Files.newByteChannel(Files.java:370)
	at java.nio.file.Files.newByteChannel(Files.java:421)
	at java.nio.file.Files.readAllBytes(Files.java:3205)
	at org.scalafmt.util.FileOps$.readFile(FileOps.scala:58)
	at org.scalafmt.util.FileOps$.readFile(FileOps.scala:49)
	at org.scalafmt.cli.InputMethod$FileContents.readInput(InputMethod.scala:42)
	at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:83)
	at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:70)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:46)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:45)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1274)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:946)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:943)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

(cc https://github.com/scalameta/scalafmt/pull/2162)

**Comment by mrubin** [comment]
@kitbellew @poslegm Are you able to help with this?

**Comment by poslegm** [comment]
Should be fixed in the next release. But `scalafmt --stdin` works right now:

```
~ echo "foo" | scalafmt --stdin
stdin.scala:1: error: expected class or object definition
foo
^
```

**Comment by mrubin** [comment]
Thank you @poslegm  - I will look for this fix in the next release. Please note that your suggestion does not work - it is not an equivalent command.

According to the `help` text:

```
scalafmt --stdin # read from stdin and print to stdout
```

This is not what I need - reading a filename from stdin, formatting the file, and saving the file.

e.g:

```
scalafmt "app/Module.scala"
```

causes that file to be formatted.

```
$ echo "app/Module.scala" | scalafmt --stdin
stdin.scala:1: error: expected class or object definition
app/Module.scala
^
```

The two are not the same thing.

**Comment by kitbellew** [comment]
what about
```
cat filenames | xargs scalafmt --
```

**Comment by mrubin** [comment]
@kitbellew This does not appear to work:

```
$ echo "app/Module.scala" | xargs scalafmt --
Error: Unknown option --
Try  for more information.
```

**Comment by mrubinwch** [comment]
@kitbellew given there are no workarounds, is it possible to make a release with this fix?

**Comment by kitbellew** [comment]
> @kitbellew given there are no workarounds, is it possible to make a release with this fix?

the next release is v3.0.0, when all scala3-related changes are completed. it will take a little time.

meanwhile, i assumed you'd be able to get my previous suggestion working by trying a couple of options around `cat ... | xargs ...`. it should not be too hard to figure it out.
