### ISSUE TITLE
removeOptionalBraces doesn't work in case of partial functions as params

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalafmt#2495]
- **Version**: 3.0.0-RC2

- **Configuration**:
```
runner.dialect = "scala3"
rewrite.scala3.convertToNewSyntax = true
rewrite.rules = [RedundantBraces]
rewrite.scala3.removeOptionalBraces = yes
```

## Steps

Given code like this:
```scala
val a = List(Some(1), None, Some(3), Some(4)).map({
  case Some(x) => x match {
    case 1 => "one"
    case _ => "more than one"
  } 
  case _ => "none"
})

```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
org.scalafmt.util.FormatException: java.util.NoSuchElementException
    at org.scalafmt.FormatTests.run(FormatTests.scala:56)
    at org.scalafmt.FormatTests.$anonfun$new$3(FormatTests.scala:33)
    at org.scalafmt.FormatTests.$anonfun$new$3$adapted(FormatTests.scala:33)
    at org.scalafmt.util.CanRunTests.$anonfun$runTest$2(CanRunTests.scala:24)
Caused by: java.util.NoSuchElementException
    at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:631)
    at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
    at org.scalafmt.internal.FormatOps.distance(FormatOps.scala:961)
    at org.scalafmt.internal.BestFirstSearch.$anonfun$shouldRecurseOnBlock$1(BestFirstSearch.scala:74)
    at org.scalafmt.internal.BestFirstSearch.$anonfun$shouldRecurseOnBlock$1$adapted(BestFirstSearch.scala:71)
    at scala.Option.filter(Option.scala:319)
    at org.scalafmt.internal.BestFirstSearch.shouldRecurseOnBlock(BestFirstSearch.scala:71)
    at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:158)
    at org.scalafmt.internal.BestFirstSearch.run$1(BestFirstSearch.scala:291)
    at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:292)
    at org.scalafmt.internal.BestFirstSearch$.apply(BestFirstSearch.scala:334)
    at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$5(Scalafmt.scala:128)
    at scala.util.Try$.apply(Try.scala:210)
    at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$3(Scalafmt.scala:128)
    at scala.meta.parsers.Parsed.fold(Errors.scala:12)
    at scala.meta.parsers.Parsed.fold$(Errors.scala:11)
    at scala.meta.parsers.Parsed$Success.fold(Errors.scala:26)
    at org.scalafmt.Scalafmt$.doFormatOne(Scalafmt.scala:124)
    at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:102)
    at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:71)
    at org.scalafmt.FormatTests.run(FormatTests.scala:44)
```

## Expectation

I would like the formatted output to look like this:
```scala
val a = List(Some(1), None, Some(3), Some(4)).map(
  case Some(x) => x match {
    case 1 => "one"
    case _ => "more than one"
  } 
  case _ => "none"
)
```

## Notes

Not sure how to make it work, I can take a look later on at it, but if @kitbellew you have any suggestions they would help out tremendously.

We did some testing at Scala Center and a bunch of issues came up, some I am trying to fix in scalameta.

**Comment by tgodzik** [comment]
Another case this fails on, very similar it seems:
```scala
def foo[T](x: T): T = x
val bar =
  foo({
    val arr = new Array[String](10)
    var x = 0
    while (x < 10) {
      arr(x) = "x"
      x += 1
    }
    arr
  })
```
