### ISSUE TITLE
Unable to download the sbt plugin

### ISSUE THREAD

**Issue by vasigorc** [scalameta/scalafmt#2615]
- **Version**: 2.4.0
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.7.5
preset = IntelliJ
maxColumn = 120
continuationIndent.callSite = 2
continuationIndent.ctorSite = 4
continuationIndent.defnSite = 2
continuationIndent.extendSite = 4
continuationIndent.withSiteRelativeToExtends = 2
align.preset = more
```

## Steps

Running this command in CI:
```scala
sbt clean compile test it:test package
```

I am unable to download the plugin with the following message:

```bash
[warn] 
[warn] 	Note: Some unresolved dependen((redacted))es have extra attributes.  Check that these dependen((redacted))es exist with the requested attributes.
[warn] 		org.scalameta:sbt-scalafmt:2.4.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn] 	Note: Unresolved dependen((redacted))es path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalameta:sbt-scalafmt;sbtVersion=1.0;scalaVersion=2.12:2.4.0
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/org.scalameta/sbt-scalafmt/scala_2.12/sbt_1.0/2.4.0/ivys/ivy.xml
[error]   not found: ((redacted))/sbt-proxy/org.scalameta/sbt-scalafmt/scala_2.12/sbt_1.0/2.4.0/ivys/ivy.xml
[error]   not found: ((redacted))/libs-release/org/scalameta/sbt-scalafmt_2.12_1.0/2.4.0/sbt-scalafmt-2.4.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
...
```

## Other important parameters

Scalafmt formats code like this:
```shell
# scala version in build.sbt
scalaVersion in ThisBuild := "2.13.1"

# plugin version in plugins.sbt
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.0")

# sbt version in build.properties
sbt.version=1.3.6
```

## Notes

I also tried to adjust plugin version to scala version like this, but that didn't help.
```shell
addSbtPlugin("org.scalameta"   %% "sbt-scalafmt" % "2.4.0")
```

**Comment by tgodzik** [comment]
Thanks for reporting! Is it possible that the jar is just not available in your local repositories or proxies?

The sbt plugin can be found here:
https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.4.0/
