### ISSUE TITLE
Potential bug running against Scala.js

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalafmt#2633]
When trying to run `scalafmt` on the Scala.js code base as seen here:
https://github.com/scala-js/scala-js/pull/4522

Config: https://github.com/scala-js/scala-js/pull/4522/commits/f02a0886a203f338705b1131bf59da4a6567d417

## Steps

Given code like this:
https://github.com/ekrich/scala-js/tree/topic/scalafmt

When I run scalafmt like this:

```bash
scripts/scalafmt --test 2> diff.txt
```

## Problem

Scalafmt formats code like this:
```scala
org.scalafmt.cli.FailedToFormat: /Users/eric/workspace/scala-js/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/NameGen.scala
Caused by: org.scalafmt.Error$PreciseIncomplete: /Users/eric/workspace/scala-js/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/NameGen.scala:72: error: Unable to format file due to bug in scalafmt
    cache.getOrElseUpdate(name, {
                              ^
	at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$6(Scalafmt.scala:133)
	at scala.util.Success.flatMap(Try.scala:258)
	at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$3(Scalafmt.scala:128)
	at scala.meta.parsers.Parsed.fold(Errors.scala:12)
	at scala.meta.parsers.Parsed.fold$(Errors.scala:11)
	at scala.meta.parsers.Parsed$Success.fold(Errors.scala:26)
	at org.scalafmt.Scalafmt$.doFormatOne(Scalafmt.scala:124)
	at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:102)
	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:71)
	at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:78)
	at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:60)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:40)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:39)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1288)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:938)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:935)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.internal(Tasks.scala:169)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.internal$(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.internal(Tasks.scala:304)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.compute(Tasks.scala:304)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

## Expectation

No error. There are also quite a few "Search state exploded ..." even with the setting at `100,000`. Not sure what is a reasonable number for that or if the files can be formatted.

**Comment by ekrich** [comment]
Note: The desired logic for `binPack` is outlined in that PR.

**Comment by kitbellew** [comment]
@ekrich  I'm sorry but can you paste the code here, or link to the exact file that's failing, and the config. I trust you were not expecting us to read through the entire diff...

P.S. didn't understand about binpack. If you have a request, please submit an issue and describe it inline.

**Comment by ekrich** [comment]
@kitbellew Sure, I'll see if I can isolate the file that is failing and create a new issue for that. I will also see if I can come up with some binpack examples based on the text from Sebastien and create a separate issue for that. I will also close this after I at least come up with the first issue.
