### ISSUE TITLE
`Cannot invoke "scala.meta.Tree.tokens(scala.meta.Dialect)" because "tree" is null` error

### ISSUE THREAD

**Issue by mdedetrich** [scalameta/scalafmt#3443]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.7.0
runner.dialect = scala213
preset = default
align.preset = more
maxColumn = 120
project.git = true
align.openParenDefnSite = true
align.openParenCallSite = true
align.arrowEnumeratorGenerator = true
danglingParentheses.preset = true
rewrite.rules = [RedundantBraces, RedundantParens]
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`

## Steps

Given code like this:
The error isn't outputting the line where the problem is, but the file in question is here https://github.com/aiven/guardian-for-apache-kafka/blob/e839838a39e75077774099c9f4e999d9b051573b/core/src/test/scala/io/aiven/guardian/kafka/KafkaClusterTest.scala

## Problem

Scalafmt formats code like this:

There is no output, instead an exception is thrown
```
org.scalafmt.cli.FailedToFormat: /Users/mdedetrich/github/guardian-for-apache-kafka/core/src/test/scala/io/aiven/guardian/kafka/KafkaClusterTest.scala
Caused by: java.lang.NullPointerException: Cannot invoke "scala.meta.Tree.tokens(scala.meta.Dialect)" because "tree" is null
        at org.scalafmt.internal.FormatTokens.getHeadOpt(FormatTokens.scala:194)
        at org.scalafmt.internal.FormatTokens.tokenJustBeforeOpt(FormatTokens.scala:246)
        at org.scalafmt.internal.FormatWriter$FormatLocations.getAlignContainerParent(FormatWriter.scala:1293)
        at org.scalafmt.internal.FormatWriter$FormatLocations.getAlignContainer(FormatWriter.scala:1320)
        at org.scalafmt.internal.FormatWriter$FormatLocations.$anonfun$getAlignContainer$1(FormatWriter.scala:1340)
        at scala.Option.flatMap(Option.scala:283)
        at org.scalafmt.internal.FormatWriter$FormatLocations.getAlignContainer(FormatWriter.scala:1336)
        at org.scalafmt.internal.FormatWriter$FormatLocations.processLine$1(FormatWriter.scala:1165)
        at org.scalafmt.internal.FormatWriter$FormatLocations.alignmentTokens(FormatWriter.scala:1193)
        at org.scalafmt.internal.FormatWriter$FormatLocations.<init>(FormatWriter.scala:424)
        at org.scalafmt.internal.FormatWriter.getFormatLocations(FormatWriter.scala:139)
```

## Expectation

Scalafmt to work and not throw an exception, since the `.scalafmt` config wasn't changed I am not expecting any formatting change

## Workaround

Since I don't know which exact line is causing the issue I haven't put time into finding a workaround.

## Notes

Entire stack trace can be found at https://gist.github.com/mdedetrich/668823d5dd27a6dba47846ef30e6a990

If it wasn't clear, the only thing I did was bump the scalafmt version from 3.6.1 to 3.7.0

**Comment by mdedetrich** [comment]
Appears to be a duplicate of https://github.com/scalameta/scalafmt/issues/3439. If so feel free to close.

**Comment by kitbellew** [comment]
correct, duplicate.
