### ISSUE TITLE
exploded search state on moderate-length for-loop

### ISSUE THREAD

**Issue by jpassaro** [scalameta/scalafmt#3491]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
runner.dialect = scala213
version = 3.7.2
fileOverride {
  "glob:**.sbt" {
    runner.dialect = sbt1
  }
}
project.git = true

align.tokens."+" = [{
    code = "%"
    owners = [{
      regex = "Term.ApplyInfix"
    }]
  }, {
    code = "%%"
    owners = [{
      regex = "Term.ApplyInfix"
    }]
  }, {
    code = "->"
    owners = [{
      regex = "Term.ApplyInfix"
    }]
  }
]

indent.withSiteRelativeToExtends = 2
indent.relativeToLhsLastLine = [match, infix]
verticalMultiline.arityThreshold = 3
newlines.source = keep
newlines.selectChains = unfold

rewrite.trailingCommas.style = multiple


includeNoParensInSelectChains = true

importSelectors = binpack
```

NB: before submitting, please confirm that the problem is observed in the
*latest published* version of the formatter! We don't publish hotfixes for older
versions, and the problem you have observed in an older version may have already
been fixed.

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt <path/to/my/file>`

## Steps

Given code like this (obfuscated because it's a work project):
```scala
override def aaaa(
      aaaa: BBBBBBBBB,
      aaaa: BBBBBBBBB,
      aaaa: List[BBBBBBBBB],
      aaaa: BBBBBBBBB,
      aaaa: Option[Date],
  ): F[BBBBBBBBB] = for {
    aaaa <- (aaaa, aaaa, aaaa(aaaa)).parTupled
    (aaaa, aaaa, aaaa) = aaaa
    aaaa = this.aaaa.aaaa(BBBBBBBBB.aaaa(
      "aaaa" -> aaaa.value,
      "aaaa" -> aaaa,
      "aaaa" -> aaaa
    ))

   
   
    aaaa = aaaa.flatMap(_.aaaa).map(_.aaaa).toSet
    aaaa <- aaaa.aaaa(aaaa).adaptError(e => 
      BBBBBBBBB(
        "",
        BBBBBBBBB.BBBBBBBBB(
          BBBBBBBBB(e.toString, Some(BBBBBBBBB.BBBBBBBBB))
        )
      )
    ).flatMap(aaaa.aaaa.aaaa(_))

    aaaa = BBBBBBBBB(
      aaaa,
      aaaa,
      aaaa,
      aaaa,
      aaaa,
      aaaa.aaaa,
      aaaa,
    )
    aaaa = BBBBBBBBB(aaaa = aaaa, aaaa = aaaa.aaaa)

    aaaa <- F.both(
        aaaa.aaaa.aaaa(aaaa),
        aaaa.aaaa.aaaa(aaaa)
    )

    aaaa <- aaaa.aaaa(List(aaaa.value, aaaa, aaaa))
    _ <- aaaa.aaaa.aaaa(
      BBBBBBBBB(aaaa = aaaa.value)
    )
  } yield BBBBBBBBB(
    aaaa,
    aaaa,
    aaaa,
    aaaa,
    aaaa,
    BBBBBBBBB(
      BBBBBBBBB(aaaa),
      aaaa.BBBBBBBBB.aaaa(0),
      BBBBBBBBB.BBBBBBBBB,
      BBBBBBBBB.BBBBBBBBB,
      aaaa = None,
    ),
    aaaa,
  )
```

## Problem

Scalafmt prints a great big stack trace, naming a spot where "search state exploded", and only formats up to that point:
```
org.scalafmt.cli.FailedToFormat: /Users/jpassaro/code/vanellope/modules/server/src/main/scala/datos/vanellope/gateway/server/service/Service.scala
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded on 'jobDatabricks∙.[3353:3354]', line 97
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:179)
	at org.scalafmt.internal.BestFirstSearch.$anonfun$shortestPath$4(BestFirstSearch.scala:200)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:186)
	at org.scalafmt.internal.BestFirstSearch.run$1(BestFirstSearch.scala:301)
	at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:302)
[snip]
```

## Expectation

I would like scalafmt to finish formatting the file without incident.

## Workaround

I have not yet tried to refactor, though this is the advice on the website when running into this problem. I confess to some confusion though -- the explanation on the website blames this on deeply nested function calls. This code can only be considered to fit that description if you consider it to be so after desugaring the for loop! Is scalafmt parsing a desugared rendition of the code?

**Comment by kitbellew** [comment]
@jpassaro `Search state exploded on 'jobDatabricks∙.[3353:3354]', line 97` doesn't seem to refer to your example.

**Comment by jpassaro** [comment]
this stopped happening after i refactored and organized the code better. closing.
