### ISSUE TITLE
Orphan parens error 

### ISSUE THREAD

**Issue by jxnu-liguobin** [scalameta/scalafmt#3496]
This template is mostly a guideline, not a strict requirement, except
the sections marked `(required)`.

Please make sure that the issue is observable using the latest version of `scalafmt` and
within the `scalafmt` **CLI**: `https://scalameta.org/scalafmt/docs/installation.html#cli`

Using the CLI is _mandatory_, in one of these configurations:
- latest version of CLI and latest version in `.scalafmt.conf`
- previous version of CLI and latest version in `.scalafmt.conf`
- latest version of CLI and previous version in `.scalafmt.conf`

## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.5.9
runner.dialect = scala3
project.git = true
preset = default
maxColumn = 120
align.preset = most
align.multiline = false
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings.blankFirstLine = yes
docstrings.style = SpaceAsterisk
docstrings.removeEmpty = true
docstrings.wrap = false
docstrings.forceBlankLineBefore = true
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true
optIn.annotationNewlines = true
newlines.alwaysBeforeMultilineDef = false
rewrite.rules = [RedundantBraces]
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true
rewrite.redundantBraces.generalExpressions = false
rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}

project.excludePaths = ["glob:**/scalafix/input/**", "glob:**/scalafix/output/**"]

fileOverride {
  ".sbt" {
    runner.dialect = sbt1
  }
  "glob:**/star-sbt-plugin/src/**.scala" {
    rewrite.scala3.convertToNewSyntax = false
    rewrite.scala3.removeOptionalBraces = false
  }
  "glob:**/star-codegen/src/**.scala" {
    rewrite.scala3.convertToNewSyntax = false
    rewrite.scala3.removeOptionalBraces = false
  }
  "glob:**/project/**.scala" {
    rewrite.scala3.convertToNewSyntax = false
    rewrite.scala3.removeOptionalBraces = false
  }
}
```

NB: before submitting, please confirm that the problem is observed in the
*latest published* version of the formatter! We don't publish hotfixes for older
versions, and the problem you have observed in an older version may have already
been fixed.

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `<command-line parameter>`

If you were not using CLI initially:
- please check using `scalafmt` CLI before submitting here (required)
- if the problem does not present via CLI, DO NOT SUBMIT
  here: this is NOT a formatter issue
  - it could be an issue with your integration (sbt-scalafmt, metals, intellij etc.)
  - instead please submit the issue in the appropriate tool's repository
  - for instance, if the tool is `sbt` with the `sbt-scalafmt` plugin: please
    submit in `sbt-scalafmt` and include scalafmt parameters from `build.sbt`
    and the `sbt` command used
  - conversely, do not submit formatting issues into other tools; you must first
    verify using `scalafmt` CLI

## Steps

Given code like this:
```scala
  implicit def map: Array[Any] => List[String] = a =>
    a.map (ae => {
      ae match
        case s: String => s
        case _ => ae.toString
    }).toList
```

## Problem

Scalafmt formats code like this:
```scala
// error
Orphan parens ([412]()
```

Remove the curly brackets inside or change the curly brackets outside to curly brackets, can work normally

## Expectation

The brackets should be automatically removed
```scala
  implicit def map: Array[Any] => List[String] = a =>
    a.map (ae => 
      ae match
        case s: String => s
        case _ => ae.toString
    ).toList
```

## Workaround

I've found that by...

## Notes

See also...

**Comment by kitbellew** [comment]
@jxnu-liguobin two requests:

- could you please remove from your description the original instructions, and keep only our questions and your answers to them?
- can you please recheck your submission examples; the part containing original code doesn't correspond to scalafmt-formatted code, so it's not clear how to reproduce and what to expect

**Comment by kitbellew** [comment]
also, you seem to have ignored the instructions. version 3.5.9 is not latest. please use the latest version and verify.

**Comment by jxnu-liguobin** [comment]
> also, you seem to have ignored the instructions. version 3.5.9 is not latest. please use the latest version and verify.

Updated

**Comment by kitbellew** [comment]
> ## Problem
> get error after executing `sbt scalafmt`: <img alt="image" width="510" src="https://user-images.githubusercontent.com/29496873/224354670-612e0225-4f04-4e7f-a2f4-4822ef77ea57.png">

Can you please verify using the scalafmt command-line interface, just like the issue instructions mentioned? The error might be coming from sbt, so only CLI is requested.

**Comment by jxnu-liguobin** [comment]
./scalafmt will still get the same error
```
 org.scalafmt.cli.FailedToFormat: /Users/liguobin/Work/star-authority/star-auth-infra/src/main/scala/fc/star/auth/infra/repository/syntax/AuthPermissionTable.scala
Caused by: java.lang.IllegalArgumentException: Orphan parens ([412]()
        at org.scalafmt.util.TreeOps$.getMatchingParentheses(TreeOps.scala:210)
        at org.scalafmt.internal.FormatTokens.org$scalafmt$internal$FormatTokens$$matchingParentheses$lzycompute(FormatTokens.         Reformatting...
    4.2%at org.scalafmt.internal.FormatTokens.org$scalafmt$internal$FormatTokens$$matchingParentheses(FormatTokens.scala:24)
        at org.scalafmt.internal.FormatTokens.matchingOpt(FormatTokens.scala:80)
        at org.scalafmt.internal.FormatOps.$anonfun$getForceConfigStyle$2(FormatOps.scala:1171)
        at org.scalafmt.internal.FormatOps.$anonfun$getForceConfigStyle$2$adapted(FormatOps.scala:1161)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
        at org.scalafmt.internal.FormatTokens.foreach(FormatTokens.scala:12)
        at org.scalafmt.internal.FormatOps.getForceConfigStyle(FormatOps.scala:1161)
        at org.scalafmt.internal.FormatOps.<init>(FormatOps.scala:74)
        at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$4(Scalafmt.scala:153)
        at scala.meta.parsers.Parsed.fold(Errors.scala:12)
        at scala.meta.parsers.Parsed.fold$(Errors.scala:11)
        at scala.meta.parsers.Parsed$Success.fold(Errors.scala:26)
        at org.scalafmt.Scalafmt$.org$scalafmt$Scalafmt$$doFormatOne(Scalafmt.scala:152)
        at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:126)
        at org.scalafmt.Scalafmt$.formatCodeWithStyle(Scalafmt.scala:91)
        at org.scalafmt.Scalafmt$.$anonfun$formatCode$3(Scalafmt.scala:78)
        at scala.util.Success.fold(Try.scala:281)
        at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:78)
        at org.scalafmt.Scalafmt$.format(Scalafmt.scala:59)
        at org.scalafmt.Scalafmt.format(Scalafmt.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.scalafmt.dynamic.ScalafmtReflect.$anonfun$tryFormat$1(ScalafmtReflect.scala:110)
        at scala.util.Try$.apply(Try.scala:210)
        at org.scalafmt.dynamic.ScalafmtReflect.tryFormat(ScalafmtReflect.scala:106)
        at org.scalafmt.dynamic.ScalafmtReflectConfig.tryFormat(ScalafmtReflectConfig.scala:95)
        at org.scalafmt.dynamic.ScalafmtDynamicSession.$anonfun$tryForceFormat$1(ScalafmtDynamicSession.scala:50)
        at scala.util.Success.flatMap(Try.scala:258)
        at org.scalafmt.dynamic.ScalafmtDynamicSession.tryForceFormat(ScalafmtDynamicSession.scala:50)
        at org.scalafmt.dynamic.ScalafmtDynamicSession.tryFormat(ScalafmtDynamicSession.scala:37)
        at org.scalafmt.dynamic.ScalafmtDynamicSession.format(ScalafmtDynamicSession.scala:19)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.handleFile(ScalafmtDynamicRunner.scala:79)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$7(ScalafmtDynamicRunner.scala:52)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$7$adapted(ScalafmtDynamicRunner.scala:50)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:938)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:935)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.internal(Tasks.scala:159)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.internal$(Tasks.scala:156)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.internal(Tasks.scala:304)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.compute(Tasks.scala:304)
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)

```

**Comment by davesmith00000** [comment]
In case it helps, I was getting the same error in both the metals logs and using the cli with `scalafmt 3.5.2`, but on upgrading to `3.7.2` (after reading this issue), the problem seems to have been resolved (in my case):

```
Caused by: java.lang.IllegalArgumentException: Orphan parens ([4533]()
```

Same sort of thing as @jxnu-liguobin reported. This code (Scala 3) compiles fine and works, but showed the error during formatting:

```scala
  val applyAlpha: Layer => SignalFunction[Double, Layer] = l =>
    SignalFunction(d =>
      val material = l.blending.map(b => b.blendMaterial) match
        case Some(m) => m
        case None    => BlendMaterial.BlendEffects.None

      material match
        case m: BlendMaterial.BlendEffects =>
          l.withBlendMaterial(m.withAlpha(d))
        case _ => l
    )  // <-- Note the bracket type
```

This version works fine, all I've done is change the parenthesis to curly braces after `SignalFunction`:

```scala
  val applyAlpha: Layer => SignalFunction[Double, Layer] = l =>
    SignalFunction { d =>
      val material = l.blending.map(b => b.blendMaterial) match
        case Some(m) => m
        case None    => BlendMaterial.BlendEffects.None

      material match
        case m: BlendMaterial.BlendEffects =>
          l.withBlendMaterial(m.withAlpha(d))
        case _ => l
    }  // <-- Note the bracket type
```

**Comment by jxnu-liguobin** [comment]
> This version works fine, all I've done is change the parenthesis to curly braces after `SignalFunction`:

But It's different from my code.
```scala
  implicit def map: Array[Any] => List[String] = a =>
    a.map ( ae => {
      ae match
        case s: String => s
        case _ => ae.toString
    }
    ).toList
```
There are two kinds of brackets. Removing any one will work normally.
