### ISSUE TITLE
`scalafmt` throws error on `getPathMatcher`

### ISSUE THREAD

**Issue by KaranAhlawat** [scalameta/scalafmt#3660]
## Configuration (required) ##

```
version = 3.7.14
runner.dialect = scala3
fileOverride {
  "build.sc" {
    runner.dialect = scala213
  }
  "deps.sc" {
    runner.dialect = scala213
  }
}
rewrite {
  rules = [RedundantBraces]
  scala3 {
    convertToNewSyntax = true
    removeOptionalBraces = yes
  }
}
indent.defnSite = 2
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `cat modules/core/src/shop/programs/Checkout.scala | scalafmt-native --config .scalafmt.conf --stdin`

## Problem

Scalafmt formats code like this:
```scala
org.scalafmt.cli.FailedToFormat: stdin.scala
Caused by: java.lang.IllegalArgumentException
        at java.base@11.0.17/sun.nio.fs.UnixFileSystem.getPathMatcher(UnixFileSystem.java:286)
        at org.scalafmt.config.ScalafmtConfig$$anonfun$2.applyOrElse(ScalafmtConfig.scala:204)
        at org.scalafmt.config.ScalafmtConfig$$anonfun$2.applyOrElse(ScalafmtConfig.scala:202)
        at scala.collection.immutable.List.collect(List.scala:267)
        at org.scalafmt.config.ScalafmtConfig.$anonfun$expandedFileOverride$1(ScalafmtConfig.scala:202)
        at scala.util.Try$.apply(Try.scala:210)
        at org.scalafmt.config.ScalafmtConfig.expandedFileOverride$lzycompute(ScalafmtConfig.scala:182)
        at org.scalafmt.config.ScalafmtConfig.expandedFileOverride(ScalafmtConfig.scala:182)
        at org.scalafmt.config.ScalafmtConfig.getConfigFor(ScalafmtConfig.scala:217)
        at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:75)
        at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:67)
        at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:51)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:35)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:34)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:938)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:935)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.compute(Tasks.scala:304)
        at java.base@11.0.17/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.base@11.0.17/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base@11.0.17/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base@11.0.17/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base@11.0.17/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base@11.0.17/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

## Expectation

The formatter runs

## Workaround

Haven't found any.

## Notes

I first thought it might be an issue with me using GraalVM CE 21. Thus, I tried with GraalVM CE 17, and also  with Temurin 17. Neither worked. Using `scalafmt` through the `metals` server also runs into the same issue.

**Comment by kitbellew** [comment]
have you tried using the JVM version of scalafmt (not native)?

**Comment by KaranAhlawat** [comment]
Yes, it runs into the same issue.

**Comment by kitbellew** [comment]
can you please include all steps to reproduce the issue using a regular scalafmt that you installed using coursier (as described on the installation documentation page)?

**Comment by KaranAhlawat** [comment]
Sure, here are the steps I took

1. Install a JDK - Mine is GraalVM CE 21.
2. Install `scalafmt` - `cs install scalafmt`.
3. `scalafmt --version` outputs `3.7.14`.
4. Create a file you want to format.
5. Create a `.scalafmt.conf` file.
6. `cat /your/file/path/file.scala | scalafmt --config .scalafmt.conf --stdin`
7. Throws an exception

Expected behavior in this case is that it reads in the code from `stdin`, formats it, and then prints it out to `stdout`.

**Comment by kitbellew** [comment]
and if you do the same but without piping `cat ... | ... --stdin` but calling the formatter on this file directly (scalafmt ... file.scala)?

**Comment by kitbellew** [comment]
it works as expected. here's the link to the documentation: https://scalameta.org/scalafmt/docs/configuration.html#fileoverride. Specifically, it says: _... matching a [PathMatcher](https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-) pattern (e.g., a glob or a regex)..._

`deps.sc` is not a PathMatcher pattern.

**Comment by KaranAhlawat** [comment]
Alright! That does indeed work. Thank you.
