### ISSUE TITLE
Search state exploded

### ISSUE THREAD

**Issue by rpiaggio** [scalameta/scalafmt#3669]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = "3.7.14"
style = default

runner.dialect = scala3

maxColumn = 100
project.git = true

// Vertical alignment is pretty, but leads to bigger diffs
align.preset = most

rewrite.rules = [
  AvoidInfix
  RedundantBraces
  RedundantParens
  AsciiSortImports
  PreferCurlyFors
]

align.tokens."+" = [{code = "=>", owner = "Case"}]
align.tokens."+" = [{code = ":", owner = "Term.Param"}, "=", "shouldBe", "<-", "^"]
align.openParenCallSite = true
spaces.inImportCurlyBraces = false

continuationIndent.defnSite = 2

docstrings.style = Asterisk

rewrite.neverInfix.excludeFilters = [until
  to
  by
  eq
  ne
  "should.*"
  "contain.*"
  "must.*"
  in
  be
  taggedAs
  thrownBy
  synchronized
  have
  when
  size
  theSameElementsAs]
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt modules/web/client/src/main/scala/observe/ui/components/Home.scala  `

## Steps

```
git clone git@github.com:gemini-hlsw/observe.git
cd observe
git checkout 22a8326bb31deac271689f1f0f4ff42062a1e9b1
scalafmt modules/web/client/src/main/scala/observe/ui/components/Home.scala
```

## Problem

Scalafmt crashes:
```
org.scalafmt.cli.FailedToFormat: /Users/rpiaggio/gemini/observe/modules/web/client/src/main/scala/observe/ui/components/Home.scala
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded on '=>∙ResourceRunOperation[5200:5249]', line 131
        at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:179)
        at org.scalafmt.internal.BestFirstSearch.run$1(BestFirstSearch.scala:301)
        at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:302)
        at org.scalafmt.internal.BestFirstSearch$.apply(BestFirstSearch.scala:344)
        at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$6(Scalafmt.scala:156)
        at scala.util.Try$.apply(Try.scala:210)
        at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$4(Scalafmt.scala:156)
        at scala.meta.parsers.Parsed.fold(Errors.scala:12)
        at scala.meta.parsers.Parsed.fold$(Errors.scala:11)
        at scala.meta.parsers.Parsed$Success.fold(Errors.scala:26)
        at org.scalafmt.Scalafmt$.org$scalafmt$Scalafmt$$doFormatOne(Scalafmt.scala:152)
        at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:126)
        at org.scalafmt.Scalafmt$.formatCodeWithStyle(Scalafmt.scala:91)
        at org.scalafmt.Scalafmt$.$anonfun$formatCode$3(Scalafmt.scala:78)
        at scala.util.Success.fold(Try.scala:281)
        at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:78)
        at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:67)
        at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:51)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:35)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:34)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:938)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:935)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.compute(Tasks.scala:304)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

## Expectation

Not crashing?

## Workaround

For the moment, I had to disable scalafmt.

**Comment by kitbellew** [comment]
https://scalameta.org/scalafmt/docs/configuration.html#search-state-exploded
