### ISSUE TITLE
org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: [v3.7.16] corrupted class path

### ISSUE THREAD

**Issue by armanbilge** [scalameta/scalafmt#3689]
For example: https://github.com/typelevel/toolkit/actions/runs/6830956374/job/18579714429?pr=122#step:6:25

But this seems to be widespread 🤔

**Comment by seveneves** [comment]
The `org.scalafmt.interfaces.ScalafmtException: [v3.7.16] corrupted class path:` exception is caused by following when running `scalafmt` cli tool with scalafmt config set to `3.7.16`

```
Caused by: java.lang.ClassNotFoundException: org.scalafmt.config.Config
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.scalafmt.dynamic.ScalafmtReflect.<init>(ScalafmtReflect.scala:21)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$.$anonfun$loadClassPath$1(ScalafmtModuleLoader.scala:73)
	at scala.util.Try$.apply(Try.scala:210)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$.org$scalafmt$dynamic$ScalafmtModuleLoader$$loadClassPath(ScalafmtModuleLoader.scala:71)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$WithDownloader.$anonfun$load$2(ScalafmtModuleLoader.scala:37)
	at scala.util.Success.fold(Try.scala:281)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$WithDownloader.load(ScalafmtModuleLoader.scala:37)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$CachedProxy.load$1(ScalafmtModuleLoader.scala:56)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$CachedProxy.$anonfun$load$3(ScalafmtModuleLoader.scala:57)
	at scala.util.Try$.apply(Try.scala:210)
	at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$CachedProxy.load(ScalafmtModuleLoader.scala:57)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$.$anonfun$load$1(ScalafmtConfigLoader.scala:34)
	at scala.util.Either.flatMap(Either.scala:352)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$.load(ScalafmtConfigLoader.scala:32)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.load$1(ScalafmtConfigLoader.scala:74)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.$anonfun$load$12(ScalafmtConfigLoader.scala:76)
	at scala.util.Try$.apply(Try.scala:210)
	at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.$anonfun$load$7(ScalafmtConfigLoader.scala:76)
	at scala.util.Success.fold(Try.scala:281)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.load(ScalafmtConfigLoader.scala:70)
	at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:59)
	at org.scalafmt.dynamic.ScalafmtDynamic.createSession(ScalafmtDynamic.scala:53)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.run(ScalafmtDynamicRunner.scala:28)
```

**Comment by erikerlandson** [comment]
yeah scala steward upgraded this and it broke my CI

**Comment by seveneves** [comment]
> The `org.scalafmt.interfaces.ScalafmtException: [v3.7.16] corrupted class path:` exception is caused by following when running `scalafmt` cli tool with scalafmt config set to `3.7.16`

Updating scalafmt cli tool to the same version `3.7.16` as config file fixed the problem. I assume similar "update" would fix the sbt plugin, which just reports `corrupted class path`.

The issue seems to be related to the removal/renaming of `org.scalafmt.config.Config`.

**Comment by xuwei-k** [comment]
- https://github.com/scala-steward-org/scala-steward/pull/3210
