### ISSUE TITLE
`org.scalafmt.cli.FaliedToFormat` regression with `scala-xml` code on `RedundantBraces` rewrite rule

### ISSUE THREAD

**Issue by Gedochao** [scalameta/scalafmt#3891]
`scalafmt` 3.8.1 seems to have trouble parsing `scala-xml` code.

## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = "3.8.1"

align.preset = more
maxColumn = 100
assumeStandardLibraryStripMargin = true
indent.defnSite = 2
indentOperator.topLevelOnly = false
align.preset = more
align.openParenCallSite = false
newlines.source = keep
newlines.beforeMultiline = keep
newlines.afterCurlyLambdaParams = keep
newlines.alwaysBeforeElseAfterCurlyIf = true

runner.dialect = scala3

rewrite.rules = [
  RedundantBraces
  RedundantParens
  SortModifiers
]

rewrite.redundantBraces {
  ifElseExpressions = true
  includeUnitMethods = false
  stringInterpolation = true
}

rewrite.sortModifiers.order = [
  "private", "final", "override", "protected",
  "implicit", "sealed", "abstract", "lazy"
]

project.excludeFilters = [
  ".bloop"
  ".metals"
  ".scala-build"
  "examples" # Scala 3 scripts and using directives not supported yet
  "out"
  "scala-version.scala"
]
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`
No special parameters.

## Steps

Given this script code from the `scala-cli` repo:
https://github.com/VirtusLab/scala-cli/blob/main/.github/scripts/generate-junit-reports.sc

## Problem

Scalafmt fails with the following error:
```
scalafmt 
Router:2691 MISSING CASE:
[Xml.SpliceStart [3426..3426)            

[Ident(test) [3427..3431)                
Router:2691 MISSING CASE:
[Ident(selector) [3432..3440)            

[Xml.SpliceEnd [3441..3441)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [3452..3452)            

[Ident(test) [3453..3457)                
Router:2691 MISSING CASE:
[Ident(fullyQualifiedName) [3458..3476)  

[Xml.SpliceEnd [3477..3477)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [3483..3483)            
[LF [3484..3485)                         
[Space [3485..3486)                      
[Space [3486..3487)                      
[Space [3487..3488)                      
[Space [3488..3489)                      
[Space [3489..3490)                      
[Space [3490..3491)                      
[Ident(test) [3491..3495)                
Router:2691 MISSING CASE:
[Xml.SpliceStart [3558..3558)            

[Ident(test) [3559..3563)                
Router:2691 MISSING CASE:
[Ident(toString) [3573..3581)            

[Xml.SpliceEnd [3582..3582)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [3592..3592)            
[LF [3593..3594)                         
[Space [3594..3595)                      
[Space [3595..3596)                      
[Space [3596..3597)                      
[Space [3597..3598)                      
[Space [3598..3599)                      
[Space [3599..3600)                      
[Ident(test) [3600..3604)                
Router:2691 MISSING CASE:
[Xml.SpliceStart [3655..3655)            

[Ident(failure) [3656..3663)             
Router:2691 MISSING CASE:
[Ident(message) [3664..3671)             

[Xml.SpliceEnd [3672..3672)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [3706..3706)            

[Ident(failure) [3707..3714)             
Router:2691 MISSING CASE:
[Ident(message) [3715..3722)             

[Xml.SpliceEnd [3723..3723)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [3746..3746)            

[Ident(failure) [3747..3754)             
Router:2691 MISSING CASE:
[Ident(name) [3755..3759)                

[Xml.SpliceEnd [3760..3760)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [3779..3779)            

[Ident(failure) [3780..3787)             
Router:2691 MISSING CASE:
[Ident(fileName) [3797..3805)            

[Xml.SpliceEnd [3806..3806)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [3825..3825)            

[Ident(failure) [3826..3833)             
Router:2691 MISSING CASE:
[Ident(lineNumber) [3843..3853)          

[Xml.SpliceEnd [3854..3854)              
Router:2691 MISSING CASE:
[Ident(orNull) [3884..3890)              
[LF [3890..3891)                         
[Space [3891..3892)                      
[Space [3892..3893)                      
[Space [3893..3894)                      
[Space [3894..3895)                      
[Xml.SpliceEnd [3896..3896)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [3905..3905)            
[LF [3906..3907)                         
[Space [3907..3908)                      
[Space [3908..3909)                      
[Space [3909..3910)                      
[Space [3910..3911)                      
[Space [3911..3912)                      
[Space [3912..3913)                      
[Ident(test) [3913..3917)                
Router:2691 MISSING CASE:
[Xml.SpliceStart [3963..3963)            
[LF [3964..3965)                         
[Space [3965..3966)                      
[Space [3966..3967)                      
[Space [3967..3968)                      
[Space [3968..3969)                      
[Space [3969..3970)                      
[Space [3970..3971)                      
[Space [3971..3972)                      
[Space [3972..3973)                      
[Space [3973..3974)                      
[Space [3974..3975)                      
[Ident(failure) [3975..3982)             
Router:2691 MISSING CASE:
[Ident(orNull) [4086..4092)              
[LF [4092..4093)                         
[Space [4093..4094)                      
[Space [4094..4095)                      
[Space [4095..4096)                      
[Space [4096..4097)                      
[Xml.SpliceEnd [4098..4098)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4138..4138)            

[Ident(suit) [4139..4143)                
Router:2691 MISSING CASE:
[Ident(suit) [4139..4143)                

[Xml.SpliceEnd [4144..4144)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4150..4150)            

[Ident(suit) [4151..4155)                
Router:2691 MISSING CASE:
[Ident(suit) [4151..4155)                

[Xml.SpliceEnd [4156..4156)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4163..4163)            

[Ident(tests) [4164..4169)               
Router:2691 MISSING CASE:
[Ident(toString) [4177..4185)            

[Xml.SpliceEnd [4186..4186)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4196..4196)            
[LF [4197..4198)                         
[Space [4198..4199)                      
[Space [4199..4200)                      
[Space [4200..4201)                      
[Space [4201..4202)                      
[Ident(tests) [4202..4207)               
Router:2691 MISSING CASE:
[Ident(toString) [4235..4243)            
[LF [4243..4244)                         
[Space [4244..4245)                      
[Space [4245..4246)                      
[Xml.SpliceEnd [4247..4247)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4253..4253)            

[Ident(tests) [4254..4259)               
Router:2691 MISSING CASE:
[Ident(toString) [4280..4288)            

[Xml.SpliceEnd [4289..4289)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4297..4297)            

[Ident(testcases) [4298..4307)           
Router:2691 MISSING CASE:
[Ident(testcases) [4298..4307)           

[Xml.SpliceEnd [4308..4308)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4352..4352)            

[Ident(id) [4353..4355)                  
Router:2691 MISSING CASE:
[Ident(id) [4353..4355)                  

[Xml.SpliceEnd [4356..4356)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4362..4362)            

[Ident(name) [4363..4367)                
Router:2691 MISSING CASE:
[Ident(name) [4363..4367)                

[Xml.SpliceEnd [4368..4368)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4375..4375)            

[Ident(tests) [4376..4381)               
Router:2691 MISSING CASE:
[Ident(toString) [4389..4397)            

[Xml.SpliceEnd [4398..4398)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4408..4408)            
[LF [4409..4410)                         
[Space [4410..4411)                      
[Space [4411..4412)                      
[Ident(tests) [4412..4417)               
Router:2691 MISSING CASE:
[Ident(toString) [4445..4453)            
[LF [4453..4454)                         
[Space [4454..4455)                      
[Xml.SpliceEnd [4455..4455)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4461..4461)            

[Ident(tests) [4462..4467)               
Router:2691 MISSING CASE:
[Ident(toString) [4488..4496)            

[Xml.SpliceEnd [4497..4497)              
Router:2691 MISSING CASE:
[Xml.SpliceStart [4501..4501)            

[Ident(suites) [4502..4508)              
Router:2691 MISSING CASE:
[Ident(suites) [4502..4508)              

[Xml.SpliceEnd [4509..4509)              
org.scalafmt.cli.FailedToFormat: /Users/pchabelski/IdeaProjects/scala-cli-tests/scalafmt-381/generate-junit-reports.sc
Caused by: org.scalafmt.Error$PreciseIncomplete: <input>:100: error: Unable to format file due to bug in scalafmt
    <testcase id={test.selector} classname={test.fullyQualifiedName} name={
                 ^
        at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$6(Scalafmt.scala:163)
        at scala.util.Success.flatMap(Try.scala:266)
        at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$3(Scalafmt.scala:158)
        at scala.meta.parsers.Parsed.fold(Errors.scala:11)
        at scala.meta.parsers.Parsed.fold$(Errors.scala:10)
        at scala.meta.parsers.Parsed$Success.fold(Errors.scala:25)
        at org.scalafmt.Scalafmt$.doFormatOne(Scalafmt.scala:154)
        at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:128)
        at org.scalafmt.Scalafmt$.formatCodeWithStyle(Scalafmt.scala:108)
        at org.scalafmt.Scalafmt$.$anonfun$formatCode$3(Scalafmt.scala:81)
        at scala.util.Success.fold(Try.scala:289)
        at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:81)
        at org.scalafmt.Scalafmt$.format(Scalafmt.scala:59)
        at org.scalafmt.Scalafmt.format(Scalafmt.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.scalafmt.dynamic.ScalafmtReflect.$anonfun$tryFormat$1(ScalafmtReflect.scala:121)
        at scala.util.Try$.apply(Try.scala:210)
        at org.scalafmt.dynamic.ScalafmtReflect.tryFormat(ScalafmtReflect.scala:117)
        at org.scalafmt.dynamic.ScalafmtReflectConfig.tryFormat(ScalafmtReflectConfig.scala:95)
        at org.scalafmt.dynamic.ScalafmtDynamicSession.$anonfun$tryForceFormat$1(ScalafmtDynamicSession.scala:49)
        at scala.util.Success.flatMap(Try.scala:258)
        at org.scalafmt.dynamic.ScalafmtDynamicSession.tryForceFormat(ScalafmtDynamicSession.scala:49)
        at org.scalafmt.dynamic.ScalafmtDynamicSession.tryFormat(ScalafmtDynamicSession.scala:36)
        at org.scalafmt.dynamic.ScalafmtDynamicSession.format(ScalafmtDynamicSession.scala:18)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.handleFile(ScalafmtDynamicRunner.scala:76)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$7(ScalafmtDynamicRunner.scala:49)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$7$adapted(ScalafmtDynamicRunner.scala:47)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:938)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:935)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.compute(Tasks.scala:304)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

## Expectation
`scalafmt` shouldn't fail.

**Comment by Gedochao** [comment]
Managed to minimize the configuration replicating this problem to the following:
```
version = "3.8.1"
runner.dialect = scala3
rewrite.rules = [
  RedundantBraces
]
```
Removing the `RedundantBraces` rewrite rule makes the error go away.

**Comment by Gedochao** [comment]
Further minimization:
`.scalafmt.conf`:
```
version = "3.8.1"
runner.dialect = scala3
rewrite.rules = [
  RedundantBraces
]
```

Scala code:
```scala
//> using scala 3
//> using dep org.scala-lang.modules::scala-xml:2.2.0

val id = "com.example.MyTest"
<testcase id={id}/>
```

The `RedundantBraces` rewrite rule seems to be what breaks.

**Comment by Gedochao** [comment]
Extra note: this error doesn't seem to fail the actual `scalafmt` CLI and returns with exit code 0, which makes it very easy to miss it on the CI.
running
```bash
scalafmt --check
```
logs all the errors and then doesn't fail the CI job.

**Comment by kitbellew** [comment]
> Extra note: this error doesn't seem to fail the actual `scalafmt` CLI and returns with exit code 0, which makes it very easy to miss it on the CI. running
> 
> ```shell
> scalafmt --check
> ```
> 
> logs all the errors and then doesn't fail the CI job.

I couldn't reproduces this part. After running this, I do `echo $?` and get 8.

But if you add `runner.ignoreWarnings = true`, then you get 0.
