### ISSUE TITLE
Add a literals.binary setting

### ISSUE THREAD

**Issue by charpov** [scalameta/scalafmt#4176]
Now that Scala supports binary literals (as of 1.5.0) of the form `0b1101`, it'd be nice to add a `literals.binary` setting similar to `literals.float`, `literals.long`, etc.

**Comment by charpov** [comment]
It looks small enough that I decided to try to implement it myself, but my fresh fork of the repository cannot be compiled:

```
[info] welcome to sbt 1.9.9 (Temurin Java 1.8.0_422)
[info] loading settings for project scalafmt-build from plugins.sbt ...
[info] loading project definition from /Users/charpov/GIT/scalafmt/project
[info] loading settings for project scalafmt from build.sbt ...
fatal: No names found, cannot describe anything.
java.lang.RuntimeException: Nonzero exit value: 128
	at scala.sys.package$.error(package.scala:30)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:138)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:108)
	at $2ab167fe5391e31fdcae$.parseTagVersion(build.sbt:7)
	at $2ab167fe5391e31fdcae$.localSnapshotVersion(build.sbt:9)
	at $62dbcf029f1641f0b1cb$.$anonfun$$sbtdef$1(/Users/charpov/GIT/scalafmt/build.sbt:17)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:229)
	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:171)
	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:88)
	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:100)
	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[error] Nonzero exit value: 128
```
Is there a description somewhere of how to properly build the project? I did check <https://scalameta.org/scalafmt/docs/contributing-scalafmt.html>.

**Comment by kitbellew** [comment]
a mystery! i haven't seen an error like that. simply check out, and run sbt test. i use brew to install packages.

**Comment by kitbellew** [comment]
my output looks a bit like this:
```
$ sbt compile
info] welcome to sbt 1.9.9 (Eclipse Adoptium Java 18.0.1)
[info] loading global plugins from <HOME>/.sbt/1.0/plugins
[info] loading settings for project scalafmt-build from plugins.sbt ...
[info] loading project definition from <CWD>/project
[info] compiling 2 Scala sources to <CWD>/project/target/scala-2.12/sbt-1.0/classes ...
```

**Comment by kitbellew** [comment]
keep in mind that the build uses git, and this error is mentioned here: https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything

**Comment by charpov** [comment]
My bad. GitHub fork has a "fork main only" option selected by default, and my fork had no tags.

Note that the contributing documentation says to use ancient Java 8 (I even installed it on my machine for this purpose!) but the code cannot be compiled with Java 8 (it uses `String#stripTrailing` which appeared in Java 11). I compiled and ran the tests with Java 21 instead.

Now back to trying to implement my own feature request...

**Comment by charpov** [comment]
I have the implementation, test and docs in my fork (https://github.com/charpov/scalafmt/tree/format-bin-literals). All I need now is to figure out the PL...

**Comment by charpov** [comment]
Done (in <https://github.com/scalameta/scalafmt/pull/4183>).
