### ISSUE TITLE
Class `javax.net.ssl.SSLException` not found when using ScalaFmt dynamic 

### ISSUE THREAD

**Issue by sfali23** [scalameta/scalafmt#4611]
When using ScalaFmt dynamic (version **3.8.3**) to format getting following exception:

```
Exception in thread "coursier-pool-1-thread-3" java.lang.NoClassDefFoundError: javax/net/ssl/SSLException
	at coursierapi.shaded.coursier.cache.FileCache$.helper$2(FileCache.scala:1010)
	at coursierapi.shaded.coursier.cache.FileCache$.coursier$cache$FileCache$$downloading(FileCache.scala:1029)
	at coursierapi.shaded.coursier.cache.FileCache.doDownload$1(FileCache.scala:318)
	at coursierapi.shaded.coursier.cache.FileCache.$anonfun$download$54(FileCache.scala:505)
	at coursierapi.shaded.coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:53)
	at coursierapi.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:76)
	at coursierapi.shaded.coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:506)
	at coursierapi.shaded.scala.concurrent.Future$.$anonfun$apply$1(Future.scala:661)
	at coursierapi.shaded.scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: javax.net.ssl.SSLException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 12 more
```

With version **3.2.1** it works. I have tried few versions between 3.2.1 and 3.8.3 all have same problem

## Configuration (required) ##
My scala fmt file is

```
version=3.8.3
```

Although following will work

```
version=3.2.1
```

In either case the scalafmt dynamic version is **3.8.3**

Any idea what's going on.

Regards

Syed

**Comment by kitbellew** [comment]
3.8.3 is not the latest version, so please retry with the latest. 

also, what's the version of your scalafmt binary? is it latest or previous?

**Comment by sfali23** [comment]
With following configuration and using `3.8.4-RC3` binary version, still gets same error.

```
version=3.8.4-RC3
maxColumn = 120
docstrings.style = SpaceAsterisk
preset = IntelliJ
runner.dialect=Scala213Source3
// If true, the margin character | is aligned with the opening
// triple quote """ in interpolated and raw string literals.
assumeStandardLibraryStripMargin = true

optIn {
  annotationNewlines = true
  configStyleArguments = true
}

includeCurlyBraceInSelectChains = true
includeNoParensInSelectChains = true

continuationIndent {
  callSite = 2
  defnSite = 2
  ctorSite = 2
}

// Set to `none` setting to minimize git diffs/conflicts from
// renamings and other refactorings.
align = none
align {
  stripMargin = true
  tokens = [caseArrow]
  arrowEnumeratorGenerator = false
  openParenCallSite = false
  openParenDefnSite = false
}

newlines {
  avoidForSimpleOverflow = [
    punct
    slc
    tooLong
  ]
  topLevelStatementBlankLines = []
  alwaysBeforeElseAfterCurlyIf = false
  implicitParamListModifierForce = [after]
}

rewrite {
  rules = [
    PreferCurlyFors
    RedundantBraces
    RedundantParens
  ]
  redundantBraces.stringInterpolation = true
}

verticalMultiline {
  arityThreshold = 100
  newlineAfterOpenParen = false
  atDefnSite = true
  newlineAfterOpenParen = false
}

// Configure which source files should be formatted in this project.

project {
  git = true
  includeFilters = [
    ".*\\.scala$"
    ".*\\.sbt$"
  ]
  excludeFilters = []
}

// Miscellaneous

binPack.literalArgumentLists = false

spaces {
  afterKeywordBeforeParen = true
  inImportCurlyBraces = false
}
```

**Comment by kitbellew** [comment]
if you are using 3.8.4-rc3 as both binary version and the one in the config file, you shouldn't be getting any dynamic errors.

what does `scalafmt -version` say?

**Comment by sfali23** [comment]
I am programatically formatting generated code:

https://github.com/sfali/grpc-rest-gateway/blob/main/code-gen/src/main/scala/com/improving/grpc_rest_gateway/compiler/utils/Formatter.scala

I am not running from command line.

**Comment by kitbellew** [comment]
thank you for clarifying that. i don't think there's anything we could help with, unfortunately.

p.s. https://github.com/sfali/grpc-rest-gateway/blob/main/project/Dependencies.scala#L18 shows 3.8.3, not latest.

**Comment by sfali23** [comment]
Just when I ran with version `3.8.4-rc3` I updated all the dependencies to `3.8.4-rc3` including in conf file as well. I reverted it because it breaks the build

**Comment by kitbellew** [comment]
i could only suggest asking this question on the coursier project.
