### ISSUE TITLE
Strange error messages, with Exception#getMessage containing only a… number?

### ISSUE THREAD

**Issue by michalrus** [scalameta/scalafmt#564]
**Version**: 0.4.8
**Integration**: sbt
**Configuration**:

```
style = "defaultWithAlign"
maxColumn = 80
rewriteTokens = {
  "=>" = "⇒"
  "->" = "→"
  "<-" = "←"
}
```

So I can’t really provide any minimal example, hell, I can’t even reproduce it consistently, but maybe you’ll have an idea, what might be causing this behavior. Running `sbt scalafmt` _sometimes_ produces:

```
[info] Done updating.
[info] Formatting 3 Scala sources {file:/home/m/Development/…/}root ...
[warn] Scalafmt210.scala:51      Failed to format file …/Broker.scala. Cause: 817.
[success] Total time: 3 s, completed Oct 27, 2016 3:01:12 PM
```

And that’s it. :astonished: Maybe there could be an option to show the whole stack trace, not just the message?

**Comment by olafurpg** [comment]
What happens with `runner.fatalWarnings = true` or `--debug` in the cli?

**Comment by olafurpg** [comment]
Whoops, accidentally closed issue :p

**Comment by michalrus** [comment]
I bumped version to 0.4.8, and after adding these to `/.scalafmt.conf`:

```
runner = {
  fatalWarnings = true
  debug = true
}
```

… nothing changes:

```
[info] Formatting 2 Scala sources {file:/home/m/Development/…/}root ...
[warn] Scalafmt210.scala:51      Failed to format file …/Broker.scala. Cause: 817.
[success] Total time: 3 s, completed Oct 27, 2016 3:18:36 PM
```

Should I still try `--debug` with the CLI version?

**Comment by olafurpg** [comment]
fatalWarnings is only used by the cli.

**Comment by michalrus** [comment]
Oh, OK!

So it’s an `ArrayIndexOutOfBoundsException`. =)

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 817
        at org.scalafmt.internal.FormatWriter.alignmentTokens(FormatWriter.scala:259)
        at org.scalafmt.internal.FormatWriter.reconstructPath(FormatWriter.scala:135)
        at org.scalafmt.internal.FormatWriter.mkString(FormatWriter.scala:23)
        at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:209)
        at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:275)
        at org.scalafmt.Scalafmt$.format(Scalafmt.scala:57)
        at org.scalafmt.cli.Cli$.org$scalafmt$cli$Cli$$handleFile(Cli.scala:131)
        at org.scalafmt.cli.Cli$$anonfun$runFormat$1.apply(Cli.scala:190)
        at org.scalafmt.cli.Cli$$anonfun$runFormat$1.apply(Cli.scala:188)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

However, I have no idea, how to start minimizing this… =(

**Comment by olafurpg** [comment]
Did you manage to find a minimal repro?

**Comment by michalrus** [comment]
No, unfortunately not. =(

**Comment by jeantil** [comment]
Hello, I just encountered this issue with some of my production code. I have been able to isolate the problem to a single method call  in a class. Do you need a compilable sample or just the file which presents the error ?

**Comment by olafurpg** [comment]
awesome! it does not have to compile, only parse

**Comment by jeantil** [comment]
```
package net.some.company
package batch.scoring

case class ScoringSourceSample(country: String, lang: String, db: Driver.backend.Database) {
  private val tyresWithScoreQuery = tyresWithPatternsAndVehicleQuery
    .join(PerformanceQueries).on { case ((_, pattern, _), perf) => PatternQueries.withPerformance(pattern, perf) }.map { case ((tyre, pattern, vehicle), performance) => (tyre, pattern, vehicle, performance) }
    .map { case (tyre, pattern, vehicle, perf) => (tyre, pattern.numericData, pattern.description, vehicle, perf) }
}
```

conf 
```
style = defaultWithAlign # For pretty alignment.
maxColumn = 100          # For my wide 30" display.
```

**Comment by jeantil** [comment]
were you able to reproduce this ?

**Comment by olafurpg** [comment]
I am unable to reproduce @jeantil. Please reopen if this issue is still a problem
```
bash-3.2$ ../scalafmt --version
scalafmt 1.1.0
bash-3.2$ cat .scalafmt.conf
style = defaultWithAlign # For pretty alignment.
maxColumn = 100          # For my wide 30" display.
bash-3.2$ ../scalafmt --stdout -c .scalafmt.conf foo.scala
package net.some.company
package batch.scoring

case class ScoringSourceSample(country: String, lang: String, db: Driver.backend.Database) {
  private val tyresWithScoreQuery = tyresWithPatternsAndVehicleQuery
    .join(PerformanceQueries)
    .on { case ((_, pattern, _), perf) => PatternQueries.withPerformance(pattern, perf) }
    .map { case ((tyre, pattern, vehicle), performance) => (tyre, pattern, vehicle, performance) }
    .map {
      case (tyre, pattern, vehicle, perf) =>
        (tyre, pattern.numericData, pattern.description, vehicle, perf)
    }
}
```

**Comment by jeantil** [comment]
@olafurpg I tested with scalafmt 1.1.0 and I confirm that I couldn't reproduce either
