### ISSUE TITLE
Add -i/--in-place is confusingly not required?

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#814]
- **Version**: 0.6.2
- **Integration**: CLI
- **Configuration**:
```
maxColumn = 500
project.git = true
```

## Steps

I ran scalafmt like this:

```bash
scalafmt --debug
```

## Problem

Scalafmt started modifying all my code in place.

## Expectation

Because of the presence of the opt-in `-i`/`--in-place` option, and no other reason to think otherwise, I expected Scalafmt to start spewing out properly-formatted code to the standard out rather than modifying my files in place.

## Workaround

My use case was I wanted to inspect the configuration using `--debug`, my workaround is to run scalafmt like this:

```bash
scalafmt --debug -c .scalafmt.conf -f f
```

This way I don't need to `git checkout` every time, I "just" get this nonsense at the end to ignore:

```
Exception in thread "main" java.io.FileNotFoundException: /d/sbt-0.13/f (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:120)
	at org.scalafmt.util.FileOps$.readFile(FileOps.scala:63)
	at org.scalafmt.util.FileOps$.readFile(FileOps.scala:51)
	at org.scalafmt.cli.InputMethod$FileContents.readInput(InputMethod.scala:40)
	at org.scalafmt.cli.Cli$.org$scalafmt$cli$Cli$$handleFile(Cli.scala:139)
	at org.scalafmt.cli.Cli$$anonfun$runFormat$1.apply(Cli.scala:217)
	at org.scalafmt.cli.Cli$$anonfun$runFormat$1.apply(Cli.scala:215)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

## Notes

None

**Comment by olafurpg** [comment]
I agree this is confusing. `-i` currently is currently enabled by default unless you use `--files`. I made it this way since the CLI is optimized for formatting all files in a repo. I don't think it's ever useful to print out the formatted output of multiple files.

 I've struggled to find a good way to distinguish between `./scalafmt --files foo.scala` and `./scalafmt`. I've thought about using commands: `./scalafmt all` instead of `./scalafmt` and `scalafmt files foo.scala bar.scala` instead of `./scalafmt --files foo.scala,bar.scala`. The thing is that the `all` command should have `-i` set by default and `files` command `-i` is disabled.

Cleaning up the command line flags is definitely something I'd like to take should be done before v1.0 #730.

**Comment by olafurpg** [comment]
The reason why I'm not fully convinced by `./scalafmt all` is that I like the simplicity of `./scalafmt` being almost the only command most users will ever need (in combination with `--test`).

**Comment by dwijnand** [comment]
`all` can be the implied, default command. Then under `all` `-i` is a no-op.

**Comment by olafurpg** [comment]
The `-i` logic can be fixed here: https://github.com/olafurpg/scalafmt/blob/b32563fcc9283e4e9d471ad3cc4f9a72a36dd4cf/cli/src/main/scala/org/scalafmt/cli/CliOptions.scala#L37-L43

There is no good reason why it's so complicated. I think it may be because I wanted to also have `-i` be inferred to true when I did `./scalafmt --config .scalafmt`.

**Comment by olafurpg** [comment]
`-i` is enabled by default since 1.0.0-RC3
