### ISSUE TITLE
Print unified diff on --test failure

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#912]
```
./scalafmt --test --diff                                                                                      1   master
Exception in thread "main" org.scalafmt.Error$MisformattedFile: /Users/ollie/dev/scalafix/build.sbt is mis-formatted. To fix this, run `./scalafmt` from the project base directory
	at org.scalafmt.cli.InputMethod$FileContents.write(InputMethod.scala:47)
	at org.scalafmt.cli.Cli$.org$scalafmt$cli$Cli$$handleFile(Cli.scala:144)
	at org.scalafmt.cli.Cli$$anonfun$runFormat$1.apply(Cli.scala:217)
	at org.scalafmt.cli.Cli$$anonfun$runFormat$1.apply(Cli.scala:215)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
it would be nice if that error showed the actual diff instead of stack trace.

If someone wants to take a swing at this, a good place would be to see how unified diffs are created in the test suite here https://github.com/scalameta/scalafmt/blob/908ca6178d7e14c7f12bf29ffe54cb7004c958f4/scalafmt-tests/src/test/scala/org/scalafmt/util/DiffAssertions.scala#L56 using Google's javadiff library. We could depend on that library in scalafmt-cli.

A good place to test this would be in CliTest using the same infrastructure as these tests https://github.com/scalameta/scalafmt/blob/908ca6178d7e14c7f12bf29ffe54cb7004c958f4/scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala#L333

**Comment by retronym** [comment]
A few more usability suggestions:

 - Don't show the error in SBT with a stack trace.
 - Tell the user what SBT command to run to reformat.

Now:

```
[error] org.scalafmt.Error$MisformattedFile: /drone/src/github.com/sbt/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala is mis-formatted. 
150s
1032
[error] 	at org.scalafmt.cli.InputMethod$FileContents.write(InputMethod.scala:51)
150s
1033
[error] 	at org.scalafmt.cli.Cli$.handleFile(Cli.scala:118)
150s
1034
[error] 	at org.scalafmt.cli.Cli$.$anonfun$run$1(Cli.scala:175)
150s
1035
[error] 	at org.scalafmt.cli.Cli$.$anonfun$run$1$adapted(Cli.scala:173)
150s
1036
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
150s
1037
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
150s
1038
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
150s
1039
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
150s
1040
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
150s
1041
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
150s
1042
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
150s
1043
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
150s
1044
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
150s
1045
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
150s
1046
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
150s
1047
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
150s
1048
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
150s
1049
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
150s
1050
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
150s
1051
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
150s
1052
[error] 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
150s
1053
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
150s
1054
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
150s
1055
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
150s
1056
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
150s
1057
[error] org.scalafmt.Error$MisformattedFile: /drone/src/github.com/sbt/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala is mis-formatted.
```

Suggested:

```
[error] /drone/src/github.com/sbt/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala is mis-formatted. Run `sbt ...` to reformat the files.
```

**Comment by olafurpg** [comment]
Thanks for the suggestions @retronym I agree the stack trace should be hidden. The error message can be customized with the `onTestFailure` setting in .scalafmt.conf 
https://github.com/scalameta/scalafmt/blob/c5e144ebd9800effea82b302840b49dcec38125a/.scalafmt.conf#L12
The actual command depends on what integration is used (cli/sbt/maven/...)
