### ISSUE TITLE
Could not initialize class scala.meta.package$ on 2.12:0.7.0-RC1

### ISSUE THREAD

**Issue by anna-zzz** [scalameta/scalafmt#948]
Same issue as in #943?
```
$ coursier launch com.geirsson:scalafmt-cli_2.11:1.0.0-RC1 --main org.scalafmt.cli.Cli -- --test
``` 
outputs some misformatted files.

```
$ coursier launch com.geirsson:scalafmt-cli_2.12:0.7.0-RC1 --main org.scalafmt.cli.Cli -- --test
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class scala.meta.package$
    0.0%at org.scalafmt.Scalafmt$.format(Scalafmt.scala:47)
	at org.scalafmt.cli.Cli$.handleFile(Cli.scala:144)
	at org.scalafmt.cli.Cli$.$anonfun$runFormat$1(Cli.scala:220)
...
```
```
$ coursier launch com.geirsson:scalafmt-cli_2.12:0.7.0-RC1 --main org.scalafmt.cli.Cli -- --version 
scalafmt 0.7.0-RC1
```
I've cleared `~/.ivy2` and `~/.coursier` before testing.

With coursier cache in a random dir:
```
[/tmp/z]$ export COURSIER_CACHE=$(pwd)/.coursier
[/tmp/z]$ coursier launch com.geirsson:scalafmt-cli_2.12:0.7.0-RC1 --main org.scalafmt.cli.Cli -- --test                                                                        
Exception in thread "main" java.lang.NoSuchMethodError: scala.meta.io.Api.$init$(Lscala/meta/io/Api;)V
	at scala.meta.package$.<init>(package.scala:3)
	at scala.meta.package$.<clinit>(package.scala)
	at org.scalafmt.Scalafmt$.format(Scalafmt.scala:47)
	at org.scalafmt.cli.Cli$.handleFile(Cli.scala:144)
	at org.scalafmt.cli.Cli$.$anonfun$runFormat$1(Cli.scala:220)
	at org.scalafmt.cli.Cli$.$anonfun$runFormat$1$adapted(Cli.scala:218)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
Doesn't fail if there are no scala files in directory, but yields the above if I place one there.

**Comment by olafurpg** [comment]
Did you try this? https://github.com/scalameta/scalafmt/issues/943#issuecomment-304398039

**Comment by anna-zzz** [comment]
Oh. Sorry. I replaced RC for 2.11 command, not 2.12.
Do you plan to update http://scalameta.org/scalafmt/#Installation ?

**Comment by olafurpg** [comment]
Good catch! I've updated the website now, thanks. Changelog or 1.0 will follow later :)
