### ISSUE TITLE
project.git=true inside git repo causes FNFEs

### ISSUE THREAD

**Issue by anna-zzz** [scalameta/scalafmt#960]
Scalafmt fails to correctly detect path for files if project is under git and `project.git=true`

### Workspace
```
[/tmp/scalafmt-git-test]$ tree -a
.
├── bin
│   └── scalafmt
├── .git
│   └── <standard git stuff, skipping>
└── scala-sources
    └── build.sbt

[/tmp/scalafmt-git-test]$ bin/scalafmt --version
scalafmt 1.0.0-RC1

[/tmp/scalafmt-git-test]$ git --version
git version 2.13.0
````

### `project.git=false` → scalafmt works
```
[/tmp/scalafmt-git-test/scala-sources]$ ../bin/scalafmt --config-str 'project.git=false' --test --debug
Working directory: /tmp/scalafmt-git-test/scala-sources
Formatting files: List(FileContents(/tmp/scalafmt-git-test/scala-sources/build.sbt))
Exception in thread "main" org.scalafmt.Error$MisformattedFile: /tmp/scalafmt-git-test/scala-sources/build.sbt is mis-formatted. 
	...
```

### `project.git=true` → scalafmt fails
```
[/tmp/scalafmt-git-test/scala-sources]$ ../bin/scalafmt --config-str 'project.git=true' --test --debug
Working directory: /tmp/scalafmt-git-test/scala-sources
Formatting files: List(FileContents(/tmp/scalafmt-git-test/build.sbt))
Exception in thread "main" java.io.FileNotFoundException: /tmp/scalafmt-git-test/build.sbt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.scalafmt.util.FileOps$.readFile(FileOps.scala:63)
	at org.scalafmt.util.FileOps$.readFile(FileOps.scala:51)
	at org.scalafmt.cli.InputMethod$FileContents.readInput(InputMethod.scala:40)
	at org.scalafmt.cli.Cli$.handleFile(Cli.scala:112)
	at org.scalafmt.cli.Cli$.$anonfun$run$1(Cli.scala:175)
	at org.scalafmt.cli.Cli$.$anonfun$run$1$adapted(Cli.scala:173)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	...
```
For some reason, drops `scala-sources` from path

### Reproducible setup

```
[/tmp]$ mkdir -p scalafmt-git-test/{bin,scala-sources}

[/tmp]$ cd scalafmt-git-test

[/tmp/scalafmt-git-test]$ coursier bootstrap com.geirsson:scalafmt-cli_2.12:1.0.0-RC1 -o bin/scalafmt -f --main org.scalafmt.cli.Cli

[/tmp/scalafmt-git-test]$ cat > scala-sources/build.sbt
lazy val root   =    (project in file("."))

[/tmp/scalafmt-git-test]$ git init && git add . && git commit -am "Init"
Initialized empty Git repository in /tmp/scalafmt-git-test/.git/
[master (root-commit) e1b9d2a] Init
 2 files changed, 1 insertion(+)
 create mode 100755 bin/scalafmt
 create mode 100644 scala-sources/build.sbt
```

**Comment by pjrt** [comment]
So it looks like https://github.com/scalameta/scalafmt/issues/927 wasn't actually fixed. Bummer.

**Comment by anna-zzz** [comment]
@olafurpg @pjrt can you make a new version so I can test it?

**Comment by olafurpg** [comment]
@anna-zzz you can build the fatjar locally with `cli/assembly` I won't have time today to release RC2, I will try to get it out in the coming week

**Comment by anna-zzz** [comment]
I'd love RC2 as I'm including scalafmt as a coursier-pulled "dependency" in my project!

**Comment by olafurpg** [comment]
I just published RC2 and enabled auto-publish pre-releases on merge to hopefully not block again like this https://github.com/scalameta/scalafmt/pull/968 The changelog is still behind tho, #970
